.TH "jmbde" "1" "Jan 2018" "" ""
.
.SH "NAME"
\fBjmbde\fR \- tile map editor
.
.SH "SYNOPSIS"
\fBtiled\fR [\fIOPTIONS\fR]]
.
.SH "DESCRIPTION"
jmbde is a tool to collect data of a company
.
.SH "OPTIONS"
.
.TP
\fB\-h\fR \fB\-\-help\fR
Displays the help
.
.TP
\fB\-v\fR \fB\-\-version\fR
Displays the version
.
.
.SH "AUTHORS"
\fIhttps://github\.com/jmuelbert/jmbde-QT/blob/master/AUTHORS\fR
.
.SH "SEE ALSO"
