---
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 10
    commit-message:
      include: scope
      prefix: fix(gha)

  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(docker)"

  - package-ecosystem: "bundler" # See documentaton for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "fix(bundler)"

  # Maintain dependencies for nuget
  - package-ecosystem: nuget # See documentation for possible values
    directory: / # Location of package manifests
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(nuget)

  # Maintain dependencies for pip
  - package-ecosystem: pip # See documentation for possible values
    directory: / # Location of package manifests
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(pip)

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(npm)

  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /pages
    schedule:
      interval: monthly
    commit-message:
      prefix: fix(npm for astrodoc)
