---
lang/ruby:
  - examples/ruby/**
  - src/compiler/ruby*
  - src/ruby/**
  - Formula/**

pr/dependencies:
  - vendor/**/*
  - go.*
test:
  - src/**/*.spec.js
theme/contributing:
  - .github/**/*
# theme/kubernetes:
# theme/mesh-gw:
# theme/operator-usability:
# theme/performance:
# theme/service-metadata:
# theme/streaming:
# theme/terminating-gw:
theme/testing:
  - ./*test*/**/*
# theme/windows:
# thinking:
# type/bug:
# type/crash:
type/docs:
  - website/**/*
  - docs/**/*
  - pages/**/*
