version: 1.0.{build}
skip_tags: false
os: Visual Studio 2017
clone_depth: 1
clone_folder: C:\jmbde-QT

branches:
  only:
      - master
      - develop

artifacts:
  - path: 'jmbde-build\src\jmbde\*win64.exe'
    name: jmbdeexe

  - path: 'jmbde-build\src\jmbde\*win64.7z'
    name: jmbde7z

deploy:
  description: 'New jmbde release.'
  provider: GitHub
  auth_token:
    secure: mPGleT8ntVsgOL8VXZ/dmdZ/G5oqK4KgNR2+vZmYhSOnzyWA/NjBgnbMiu9QWlvX
  artifact: jmbdeexe, jmbde7z
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
    
build_script:
  - git submodule update --init --recursive
  - ps: C:\jmbde-QT\resources\scripts\.appveyor-prepare-win.ps1
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"'
  - ps: C:\jmbde-QT\resources\scripts\.appveyor-build-win.ps1

on_success:
  - ps: C:\jmbde-QT\resources\scripts\.appveyor-install-win.ps1