clone_depth: 200
version: '0.4.{build}'

cache:
  - C:\Users\appveyor\.m2
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  my_secret:
    #secure: +3IhWT10lCSC4GE4gGfWt8WiZdIXuMUfaImgvQUullg=
  matrix:
    - QTDIR: C:\Qt\5.11.1\msvc2017_64
      PYTHONHOME: C:\Python37-x64
      PUSH_RELEASE: true
      JMBDE_ITCH_CHANNEL: windows-64bit
    - QTDIR: C:\Qt\5.11.1\msvc2015
      PYTHONHOME: C:\Python37
      PUSH_RELEASE: true
      JMBDE_ITCH_CHANNEL: windows-32bit           
    - QTDIR: C:\Qt\5.11.1\mingw53_32
      PYTHONHOME: C:\Python37
      MINGW: C:\Qt\Tools\mingw530_32
      PUSH_RELEASE: true
      JMBDE_ITCH_CHANNEL: windows-32bit     
    - QTDIR: C:\Qt\5.9.5\msvc2013_64
      PYTHONHOME: C:\Python37-x64
      PUSH_RELEASE: true
      JMBDE_ITCH_CHANNEL: windows-64bit
    - QTDIR: C:\Qt\5.9.5\mingw53_32
      PYTHONHOME: C:\Python37
      MINGW: C:\Qt\Tools\mingw530_32
      PUSH_RELEASE: true
      JMBDE_ITCH_CHANNEL: windows-32bit
    - QTDIR: C:\Qt\5.6\mingw49_32
      PYTHONHOME: C:\Python37
      MINGW: C:\Qt\Tools\mingw492_32
      PUSH_RELEASE: false
      JMBDE_ITCH_CHANNEL: winxp-32bit

configuration: Release

install:
  - choco install -y qbs --version 1.12.0
  - nuget install secure-file -ExcludeVersion
  - set PATH=%PATH%;%QTDIR%\bin;%MINGW%\bin

build_script:
  - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
  - set VERSION_DATE=%DATE:~10,4%.%DATE:~4,2%.%DATE:~7,2%
  - if defined APPVEYOR_REPO_TAG_NAME (set JMBDE_RELEASE=true) else (set JMBDE_SNAPSHOT=true)
  - if defined JMBDE_RELEASE set JMBDE_VERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - if defined JMBDE_RELEASE echo Building jmbde %JMBDE_VERSION%... (from %COMMITNOW%)
  - if defined JMBDE_SNAPSHOT set JMBDE_VERSION=%APPVEYOR_BUILD_VERSION%
  - if defined JMBDE_SNAPSHOT echo Building JMBDE snapshot %JMBDE_VERSION%... (from %COMMITNOW%)
  - qbs --version
  - qbs setup-toolchains --detect
  - qbs setup-qt %QTDIR%\bin\qmake.exe qt
  - qbs config defaultProfile qt
  - if defined JMBDE_RELEASE (set JMBDE_ITCH_VERSION=%JMBDE_VERSION%) else (set JMBDE_ITCH_VERSION=%VERSION_DATE%)
  - if defined JMBDE_SNAPSHOT (set JMBDE_ITCH_CHANNEL=%JMBDE_ITCH_CHANNEL%-snapshot)
  - if not defined APPVEYOR_PULL_REQUEST_NUMBER if [%APPVEYOR_REPO_BRANCH%]==[snapshot] set PUSH_TO_ITCH=true
  - qbs build --all-products config:release projects.jmbde.windowsInstaller:true
  - qbs build --all-products config:itch  projects.jmbde.version:%JMBDE_ITCH_VERSION%
  - cd util\java
  - mvn --version
  - mvn clean install
  - cd ..\..
  - dir %QTDIR\bin


after_build:
  - cd release
  - cd installer*
  - move jmbde-*.msi %APPVEYOR_BUILD_FOLDER%
  - if defined JMBDE_SNAPSHOT move appcast-win*-snapshots.xml %APPVEYOR_BUILD_FOLDER%
  - cd ..\..
  - cd itch
  - cd archive*
  - move jmbde-*.7z %APPVEYOR_BUILD_FOLDER%
  - cd ..\..
  - if defined PUSH_TO_ITCH dist\win\push-to-itch.bat

artifacts:
  - name: Installer
    path: 'jmbde-*.msi'
  - name: Archive
    path: 'jmbde-*.7z'
  - name: AppCast
    path: 'appcast-win*-snapshots.xml'

deploy:
  - provider: GitHub
    release: jmbde $(JMBDE_VERSION)
    auth_token:
      # secure: 57ahePdHlJPeOX8/MqsIg5ho4x512wvAbwRA7TkXAOav/JTHvkTG5gf8k37/883r
    artifact: /.*\.msi/
    draft: true
    on:
        appveyor_repo_tag: true
        push_release: true

# notifications:
#  - provider: Webhook
#    url: https://webhooks.gitter.im/e/6e48d432e0e0dd1b2d22