---
extraction:
    cpp:
        prepare:
            packages:
                - build-essential
                - pkg-config
                - ninja-build
                - qt5-default
                - qttools5-dev
                - qml-module-qtquick-controls
                - qml-module-qtquick-controls2
                - libqt5svg5-dev
                - qttools5-dev-tools
                - qttools5-dev
                - libqt5opengl5-dev
        configure:
            command: cmake . -GNinja
    python:
        python_setup:
            version: 3
