---
# Base Markdownlint configuration
# Extended Markdownlint configuration in doc/.markdownlint/
'default': true
'first-header-h1': true
'header-style':
  'style': atx
'ul-style':
  'style': dash
'no-trailing-spaces': false
'line-length': false
'no-duplicate-header':
  'allow_different_nesting': true
'no-trailing-punctuation':
  'punctuation': .,;:!。，；：！？
'ol-prefix':
  'style': one
'no-inline-html': false
'hr-style':
  'style': ---
'no-emphasis-as-heading': false
'first-line-h1': false
'code-block-style':
  'style': fenced
'code-fence-style':
  'style': backtick
'fenced-code-language':
  'allowed_languages': [bash, html, javascript, json, markdown, text]
  'language_only': true
'proper-names':
  'names':
    [
      Alertmanager,
      API,
      Astro,
      Auth0,
      Azure,
      Bamboo,
      Bash,
      Bitbucket,
      Bugzilla,
      CAS,
      CentOS,
      Consul,
      Debian,
      DevOps,
      Docker,
      DockerSlim,
      Elasticsearch,
      fastlane,
      GDK,
      Geo,
      Git LFS,
      git-annex,
      Git,
      GitHub,
      GitLab Geo,
      GitLab Monitor,
      GitLab Operator,
      GitLab Pages,
      GitLab Rails,
      GitLab Runner,
      GitLab Shell,
      GitLab Workhorse,
      GitLab,
      Gitleaks,
      Gmail,
      Google,
      Grafana,
      Gzip,
      Helm,
      HipChat,
      ID,
      Ingress,
      jasmine-jquery,
      JavaScript,
      Jaeger,
      Jenkins,
      Jira,
      Jira Cloud,
      Jira Server,
      jQuery,
      JSON,
      JupyterHub,
      Karma,
      Kerberos,
      Kubernetes,
      LDAP,
      Let's Encrypt,
      Markdown,
      markdown-link-check,
      markdownlint,
      Mattermost,
      Microsoft,
      Minikube,
      MinIO,
      ModSecurity,
      NGINX Ingress,
      NGINX,
      OAuth,
      OAuth 2,
      OmniAuth,
      Omnibus GitLab,
      OpenID,
      OpenShift,
      PgBouncer,
      PostgreSQL,
      PowerShell,
      Praefect,
      Prometheus,
      Puma,
      puma-worker-killer,
      Python,
      Rake,
      Redis,
      Redmine,
      reCAPTCHA,
      Ruby,
      runit,
      Salesforce,
      SAML,
      Sentry,
      Shibboleth,
      Slack,
      SMTP,
      SpotBugs,
      SSH,
      Tiller,
      TOML,
      Trello,
      Trello Power-Ups,
      TypeScript,
      Twitter,
      Ubuntu,
      Ultra Auth,
      Unicorn,
      unicorn-worker-killer,
      URL,
      WebdriverIO,
      Xcode,
      YAML,
      YouTrack,
      ZSH
    ]
  'code_blocks': false
