---
# Configuration file for MegaLinter
# See all available variables at https://oxsecurity.github.io/megalinter/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
# DISABLE:
# - COPYPASTE # Uncomment to disable checks of excessive copy-pastes
# - SPELL # Uncomment to disable checks of spelling mistakes
DISABLE_LINTERS:
  - C_CPPLINT
  - CPP_CPPLINT
  - CSHARP_DOTNET_FORMAT # Support ONLY version 6!
PRINT_ALL_FILES: false
FILTER_REGEX_EXCLUDE: '(\.automation/test|\.automation/generated|\.github/workflows|docs/javascripts|docs/overrides|docs/json-schemas|flavors|clj-kondo|TEMPLATES)'
JSON_JSONLINT_FILTER_REGEX_EXCLUDE: '(\.vscode/)'
CSS_STYLELINT_FILTER_REGEX_EXCLUDE: '(src/jmbde/wwwroot)'
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: '(src/jmbde/wwwroot)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml)'
# YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(templates/\.mega-linter\.yml|mkdocs\.yml)'
# YAML_V8R_FILTER_REGEX_EXCLUDE: '(descriptors|templates/\.mega-linter\.yml|\.codecov\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(.gitlab-ci.yml)'
BASH_FILTER_REGEX_EXCLUDE: '(lib)'
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|LICENSE)'
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: '(\.automation/generated|docs/descriptors)'
TYPESCRIPT_FILTER_REGEX_EXCLUDE: '(src/apps/translations)'
DOCKERFILE_HADOLINT_ARGUMENTS:
  '--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028
  --ignore DL3059 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039
  --ignore SC2086 --ignore SC1091 --ignore SC3046'
REPOSITORY_TRIVY_ARGUMENTS:
  - '--skip-dirs'
  - '.automation/test'
SHOW_ELAPSED_TIME: true
EMAIL_REPORTER: false
FILEIO_REPORTER: true
JSON_REPORTER: true
GITHUB_STATUS_REPORTER: true
PLUGINS:
  - https://raw.githubusercontent.com/oxsecurity/megalinter/main/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml
PRE_COMMANDS:
  - command: echo "This is MegaLinter PRE_COMMAND on own MegaLinter ! :)"
    cwd: 'root'
POST_COMMANDS:
  - command: echo "This is MegaLinter POST_COMMAND on own MegaLinter ! :)"
    cwd: 'workspace'
