language: cpp


# regex is for release tags
branches:
  only:
    - master
    - /^v(\d+\.){2}\d+$/

matrix:
  include:
    - os: linux
      cache:
        directories:
          - /var/cache/apt/archives/*.deb
        compiler: gcc
        sudo: require
        dist: trusty
        services:
          - docker
    - os: osx

  fast_finish: true
  include:
    - stage: Linux
      os: Linux
      env
git:
  submodules: true
  depth: 1
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  on:
    repo: jmuelbert/jmbde-QT
  api_key:
    secure: qdSEjb8s9tyZPY9KChCseeJiWOEyDIyhf2GTR6CXvyqU8igyP/hqggaN/umfTTycPIrKEpdxNYuGtirRhLiPHuTW7zsyphoJwclc/eJbXHEcE8q5TEGkeSVyAatkY6wLUFZ0QpIeFl0R1P8tmzDqAkyeNGHxagRG/aWIpw6BRtjnBBd0XEFW7rxRGc7Efr05r7VKo90YUsKBMKAI78/ZFW7h1e5QhPfr/FIXLe3QZUPeAKwezYaUxQ/jrWHRC4cVTJlQIpSOJO9Ct7WhGvkIEfwzFqsZ4KZbqwyzjKlOOYnRiKwXdrfdiaRQoZjav2uiMIAZZK7dShNwCd88FZe0dE/SFtvEK3BTTkNhUXQ+xiriXaPyr505QDtkWnXtZHZEOd1J/8nJaV9K5LEjjsVyMuAzd63xS1ngc0615SAkgsS1herVpVuP95jiErbNXYZumjwrasMXnxTTruY5FGA9dme+EzHPM3t56kmTdAD+FFvS7anoew5XJze+oiveibTIxE1i9vloj4vWMEmTQ2zHzdumx+DFGGCu2Q8FHaUDyuEUV0FMiD5Rf2GdJSrr0F7m1eEdjOhh+MHL/8/+vnCiWsJulEZ3zjwMDtb8lqY0nfGtPAe7OPeAxntHs2l82cDUwX18lMz2guXT5TlMVEGnCuYLUu8DKWwdoh+G2GeG24Y=
  file: 
    - jmbde-build/src/jmbde/j*.AppImage
    - jmbde-build/src/jmbde/j*.7z
before_install: "./resources/scripts/.travis-before-install.sh"
install: true
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./resources/scripts/.travis-install-linux.sh
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./resources/scripts/.travis-install-osx.sh
  && ./resources/scripts/.travis-install-osx.sh ; fi
