language: cpp
sudo: required
dist: trusty
python: 3.6
env:
  global:
  - secure: "lpfs05x6HxkxEJS/dA4k85bytYZbDF77upYZqftkI9fp1L/c3Ka/vZ8GW9Y+pUCDRBYPgdg0OWEhOA3nUnZd8l2e7CiSXwU9V3OPWT4jVdHToEXlF34uZKUyM3grr0SfeMGqQotZ7pPpnM9V1tkMcJdCEE0gQqGxmgaX5woVB8QZFpnZY8lun7Yb4wKIjH3DC4Y79+I2smQWnEb9WZtM6GuP3CsOyuiL7IUZ1hoyDvp2yi8dPSVGQGSHXmLADPFXz7BzPh2biI5Yd5rh5o4lo7KcNCvjPfCbdLK8hUsYg621FsxRjQQKsxf8fDJtMNoE4Gp1kgI8g6ebEDkfkVzM4RuZyaCo3iODunAsD06lokbhIkNBhE4mBziYUYRHhMDY+7YBsJs1oBqq6fqD5JVTBnBgxCIMStON+gtG7+s1yvnjSgo5yX/ffGjsuKxHBXCqRsgvGPSxt6e4FalVAPok5v0GhUVKgpwA4jmaqFZnmF75AHaxZI53N8RTnWAq3Z2/q7BBE8UwxEdwJQfZYEbmGrfCmoTgAqa8bDsM+kbRW0RukYP5cMKs0HbXBhWtBpSOS/TReORd/iHTsNut+vCa6i7GXktnzED35SOie22298iZSalgOZelRGTYcx1BHWE7o142NN/OZ8qXG3sq8fGjKvHtg9aIQRRW/EyQvyeEtyc="
  - CODECOV_TOKEN="af490a45-9d52-4578-8a12-55155f9e65c9"
  addons:
    coverty_scan:
      project:
        name: jmuelbert/jmbde-QT
        description: A little BDE tool
      notification_email: juergen.muelbert@gmail.com
      build_command_prepend: qmake
      build_command: make
      branch_pattern: coverity_scan
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
      - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    before_install:
      - eval "${MATRIX_EVAL}"
      - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
      - sudo add-apt-repository --yes ppa:beineri/opt-qt595-trusty
      - sudo apt-get update -qq
      # Upgrade pip
      - sudo pip install --upgrade pip
      # Codecov
      - sudo pip install codecov
    install:
      - sudo apt-get -y install qt59base qt59script qt59svg qt59imageformats qt59tools binutils zlib1g-dev
      - source /opt/qt59/bin/qt59-env.sh
      - source ./tools/ci/linux/setup-qbs.sh
      # Codecov
      - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-7 90      
    script:
      - qbs --version
      - qbs setup-toolchains --detect
      - qbs setup-qt --detect
      - qbs config defaultProfile qt-5-9-5
      - qbs -d build --all-products config:release
      # Codecov
      - ./resources/scripts/get_code_cov.sh
    after_success:
      - bash <(curl -s https://codecov.io/bash) 
      - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" -O linuxdeployqt 
      - chmod a+x linuxdeployqt 
      - unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH 
      - ./linuxdeployqt ../build/releases/install-root/jmbde/usr/share/applications/io.github.jmuelbert.jmbde.desktop -bundle-non-qt-libs -extra-plugins=imageformats/libqsvg.so -exclude-libs=libpython3.4m.so.1.0 -verbose=2 
      - ./linuxdeployqt ../build/releases/install-root/jmbde/usr/share/applications/io.github.jmuelbert.jmbde.desktop -exclude-libs=libpython3.4m.so.1.0 -appimage 
      - find ./jmbde -executable 
      - type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq 
      - mv jmbde-x86_64.AppImage jmbde-$JMBDE_VERSION-x86_64.AppImage
    deploy:
      - provider: releases
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
        draft: true        
        api_key:
          secure: pNq/95/zTpPX25pAF3ACjoIQAnvxp6xZQYCgKhKkXhuSMCSBMl7ZIrRw0BNuM1JSHe3bRV68pfF3tgTJDWtDjFj/JHAWDOAKWhc1DeEmBXVESoizaY2Hk4yrnxjFfk+XMOFgqO+iMExap4OW+kZWXP3tltjKUYzBROMU33rey6NBiYne+UNVlzC5vgy47mj7ResrS4YBl/s3nifuE9Bigp4yDYHh4/4UgXCLXuFup+PwYRQPfwZKKiac5Bk3nHXxW+8WK3b6anboyHb+eqdZMqtu5xjqOpjwroGPPuUQsRm7c4hT93yx3IIBoIHl29hdhkWJlCOQxdhnbV0Ch9E4gombkwfHGlTFAwD3SQZFkCLdtF+1hbMgp4jta09hLgSobOIHhpGjqw+CxB5epYCM7E3WC6iKSrE7yMiSEqg6V+cf3LV+B2MlSzr1HtwLe6B7542WhFoJiF0mJCCGt//Ztp2m5174s4ZwvsiXqYMgs5x5kyp1HS5NqqllxmL3dDdPlhscKWLr7zbwDG/hhDfUpfpjefmadwf6BramK66En7fe2iol/supO86alL6/WNpCtyFaTLve/DHtWfDt+XquivGZwzCAz+0XyopJc3E7Ebxi8C49dyvdrQRi+ej1s44Cm1l/qCtS90d3WyqSfp8moepbi4pwd08vw/TD5zi8+x4=
        file: j*.AppImage
        file_glob: true
        on:
          repo: jmuelbert/jmbde-QT
          tags: true   
  - os: linux
    compiler: clang
    env:
      - QMAKESPEC=linux-clang
      - MAKEFLAGS=-j2
    before_install:
      - sudo add-apt-repository --yes ppa:beineri/opt-qt563-trusty
      - sudo apt-get update -qq
      - sudo apt-get -y install qt56base qt56svg qt56tools binutils zlib1g-dev cppcheck xvfb
      - source /opt/qt56/bin/qt56-env.sh
      - qmake -version
    script:
      - qmake
      - make
      # - pushd tests/
      # - qmake
      # - make
      # - for test in `find -executable -type f`; do pushd `dirname $test`; xvfb-run -a ./`basename $test`||exit 1; popd; done
      # - popd
    after_script:
      - cppcheck --enable=all -q -Isrc/libjmbde `git ls-files src/\*.cpp`
  - os: osx
    before_install:
    - brew update
    - brew install qt
    - brew link --force qt5
    - brew install qbs
    script:
    - qbs --version
    - qbs setup-toolchains --detect
    - qbs setup-qt --detect
    - qbs config profiles.qt.baseProfile xcode-macosx-x86_64
    - qbs config defaultProfile qt-5-11-2
    - qbs -d build --all-products config:release
    # - "macdeployqt build/release/install-root/jmbde.app"
    # - pushd install
    # - ruby ../dist/macos/fixup-install-names.rb
    # - popd
    deploy:
      - provider: releases
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
        draft: true        
        api_key:
          secure: pNq/95/zTpPX25pAF3ACjoIQAnvxp6xZQYCgKhKkXhuSMCSBMl7ZIrRw0BNuM1JSHe3bRV68pfF3tgTJDWtDjFj/JHAWDOAKWhc1DeEmBXVESoizaY2Hk4yrnxjFfk+XMOFgqO+iMExap4OW+kZWXP3tltjKUYzBROMU33rey6NBiYne+UNVlzC5vgy47mj7ResrS4YBl/s3nifuE9Bigp4yDYHh4/4UgXCLXuFup+PwYRQPfwZKKiac5Bk3nHXxW+8WK3b6anboyHb+eqdZMqtu5xjqOpjwroGPPuUQsRm7c4hT93yx3IIBoIHl29hdhkWJlCOQxdhnbV0Ch9E4gombkwfHGlTFAwD3SQZFkCLdtF+1hbMgp4jta09hLgSobOIHhpGjqw+CxB5epYCM7E3WC6iKSrE7yMiSEqg6V+cf3LV+B2MlSzr1HtwLe6B7542WhFoJiF0mJCCGt//Ztp2m5174s4ZwvsiXqYMgs5x5kyp1HS5NqqllxmL3dDdPlhscKWLr7zbwDG/hhDfUpfpjefmadwf6BramK66En7fe2iol/supO86alL6/WNpCtyFaTLve/DHtWfDt+XquivGZwzCAz+0XyopJc3E7Ebxi8C49dyvdrQRi+ej1s44Cm1l/qCtS90d3WyqSfp8moepbi4pwd08vw/TD5zi8+x4=
        file: j*.app
        file_glob: true
        on:
          repo: jmuelbert/jmbde-QT
          tags: true

before_script:
  - if [[ "$TRAVIS_TAG" ]]; then export JMBDE_RELEASE=true ; fi
  - if [[ "$TRAVIS_TAG" ]]; then export JMBDE_VERSION=${TRAVIS_TAG:1} ; fi
  - if [[ "$TRAVIS_TAG" == "" ]]; then export JMBDE_VERSION=$(date "+%Y.%m.%d") ; fi
  - if [[ "$TRAVIS_BRANCH" == "snapshot" ]]; then export JMBDE_SNAPSHOT=true ; fi
