language: cpp
sudo: required
dist: trusty
os:
- linux
- osx
osx_image: xcode9.4
notifications:
  email: false
compiler:
- gcc
git:
  submodules: true
  depth: 1
deploy:
  provider: releases
  api_key:
    secure: n6gbcwACI49YMemxJHKObR2oebd88sNot4tnPXzQjdAxgvShOHQcjIGZIFOPu5aHzsl8VmdMSsEkebJvNUTuA1CB82H3HhBiHLTzv8TfjCFpIbR8jEyBfIIQhiHmzzSpZkCls4UuWfB4AR6CW2lA+pygWX2sRk98lY25bsP2PWCbIXX6PLtM3cYwL8Dj3h5gHN25mLbIwE7g29LQSkUOZfBaZkziaKXtCcWBq+iHFF2u2zdkVsyDfUNHa9WLulreqvQ+PlZCR+0viGJDdtbjmvNtx2P+S/nrzf8gIhnEfAHSL2dqn/Yi01UDxGB1l0H87UrlljUl/qceJ8CxQSDj5IVJRXyf20tbyYah9YZ7976nX8g+5gVxLpdnQYrthMl3Bled08sJy1oLY5W39kT/cW8sqcvdNOJRApgy1tWETD/5XZixCi+MDRbtTC9hSj01U07BBE6HnNL5VgxvFiAWsKuvrD95Qms4JRMlG91JLSmcXX1GevLicO7z1ZLUT2OYFQfujRjhAR2pyjRcXt5UnXRIU7ZD4ex/mbJcyy43Lyf3Vo8GuHX3pWRTWu73BxxZadZ+jhdfImyF2PMdUkJWSL3RsqifIjj/DaSaJfBk+7/gS9LWrOaVZ7Jyan2ClDe3KddIB/61sJxY7JJNJGi5XbGm/CviaS8OYJedqtsbdlo=
  on:
    repo: jmuelbert/jmbde-QT
    branch: develop
before_install: "./resources/scripts/.travis-before-install.sh"
install: true
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./resources/scripts/.travis-install-linux.sh
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./resources/scripts/.travis-install-osx.sh
  && ./resources/scripts/.travis-install-osx.sh ; fi
