language: cpp
sudo: required
dist: trusty
os:
- linux
- osx
osx_image: xcode9.4
notifications:
  email: false
compiler:
- gcc
git:
  submodules: true
  depth: 1
deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  api_key: 
  file:
  - jmbde-build/src/jmbde/jmbde*.AppImage
  - jmbde-build/src/jmbde/jmbde*.7z
  on:
    tags: true
before_install: "./resources/scripts/.travis-before-install.sh"
before_script:
    - chmod +x ./resources/scripts/.flathub-release.sh
    - chmod +x ./resources/scripts/.generate-public-headers.sh    
    - chmod +x ./resources/scripts/.travis-before-install.sh
    - chmod +x ./resources/scripts/.travis-install-linux.sh
    - chmod +x ./resources/scripts/.travis-install-osxsh
    - chmod +x ./resources/scripts/update-localizations.sh
  
  install: true
script:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./resources/scripts/.travis-install-linux.sh
  ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then chmod +x ./resources/scripts/.travis-install-osx.sh
  && ./resources/scripts/.travis-install-osx.sh ; fi
env:
  global:
    secure: gBL8ze+6pzs+2SvzlyYMpfrJ7MndzVPu3kXPKLXZVMrrt43ROpXyaDCbX8OaykWTnvb94Q7QurQ3WApzNHa1DYwtEgArH1cgR+cL4CBVmJKxVnBcqUg1sih7gR/leoiauPaEQDR/N8len59ZCvLxU75Q7jXyznS2Uo+FwV2XYow0lT7vih8Osaqg9TxRxpsNSKMe9bbwbrdSTXOymbeQXpE+GANHFKnmAceIxRSdBHsuWx99BunCR2sep7mUQtESIw5eOwTaZYm8regDNnoEYDHo+yGB9h9L/3ibLZ1jem11HPPx95stUJIeUKB5Rd7/nwhD8FRLkZBqxlOIqv6GvIzfQqFd9vg7YYn6TCRtk9s3oapBCIbVpL71fzw5a3AMiURr6f2mTp7jGh1g+8yCAmw01t7w08U77/BhhmboyMtzdvtgyg2Z110UQihyvHvi0OtqMNtBp631Eez9hRNW90UicSahsavwtpVsLherXu99aCymCpCadfdBVgQfm1yb8jTa2wzjHcA0GXDaCCJ/Q2AQFn5m5B8TkltekHTo0+p1KWfdXR5zDnuq+Vr3GTz2G8pQ0lr76BKa1fyxaniRleOoRsSwaMqlccSHk82yU24ndu0Wf6v1rIQLXlABgzOvbSaSS4F+qcdjxoxO+gfuiI9Wzt4wphKd4kDQZs8szlI=
