language: cpp
sudo: required
dist: trusty
python: 3.6
env:
  global:
  - secure: LKLAJsygybVGNwgA/xuae8B3kVLtNO+4dNGcfDVZJ7Mfej6vY6cxQ9BxHx9SSNwgrne+pXJ/jLeIM5Xj5FGWPA1RdhtDbYCzCVlJRr67U3ht2UH00KOAOjG1m+egPuF1j8Lf0rml/Bb0pb3h1IZVfT22eYvU9i3n2FW966Td/EStxcWj5mndgC6idJleYjfqOVzm7vMvwFfX7iLBbaKsfKJF/EfO9PQE1oM44aBS+62hxJD7tEafP1oInGtcfdMMQJr1cGYYm/0IfLbY0SAMz29OPHA669d1Nhw8/Z9DIm2nRp9mVrQf10GCI+uMmBnJAeaR0ZYFSjxoU6B2Z6kBTTRpfUa2dHPC77NtNZh0DvQkJoLruLhlPJ97ZNfT2GEmybWmBC2+ifpt4I5l/5cukWubgos8qvdkHqxhRZ3C5C2A5fAevk0r4uD0RTeuitGN0unbX+pQWjcsVFtUCJlDK/RWrnktjQ3X7g/63Xjv2+gdj2xjWORWmzGCk+zb0JgNaM/KqA2DQUwcWy074BU04FD79jeJgHWg+tEgcQulb7dIniVLFb0hkJSITa1KWlJd1TYpprdEKP1PzeiqoDMZwem7Ky+dWCT1hgfYRMKeldKjqsavaTYvGHwgSOYjpHbiN9VSMWfmrir8u5rXx7/CD5YpqKDDlVwAnSqUIHcEO5E=
  addons:
    coverty_scan:
      project:
        name: jmuelbert/jmbde-QT
        description: A little BDE tool
      notification_email: juergen.muelbert@gmail.com
      build_command_prepend: qmake
      build_command: make
      branch_pattern: coverity_scan
matrix:
  include:
  - os: linux
    compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    before_install:
    - eval "${MATRIX_EVAL}"
    - sudo add-apt-repository --yes ppa:beineri/opt-qt595-trusty
    - sudo apt-get update -qq
    - sudo apt-get -y install qt59base qt59script qt59svg qt59imageformats qt59tools
      binutils zlib1g-dev
    - source /opt/qt59/bin/qt59-env.sh
    - source ./tools/ci/linux/setup-qbs.sh
    script:
    - qbs --version
    - qbs setup-toolchains --detect
    - qbs setup-qt --detect
    - qbs config defaultProfile qt-5-9-5
    - qbs -d build --all-products config:release
    after_success:
    - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
      -O linuxdeployqt - chmod a+x linuxdeployqt - unset QTDIR; unset QT_PLUGIN_PATH;
      unset LD_LIBRARY_PATH - ls - ./linuxdeployqt ./jmbde/usr/share/applications/io.github.jmuelbert.jmbde.desktop
      -bundle-non-qt-libs -extra-plugins=imageformats/libqsvg.so -exclude-libs=libpython3.4m.so.1.0
      -verbose=2 - ./linuxdeployqt ./jmbde/usr/share/applications/io.github.jmuelbert.jmbde.desktop
      -exclude-libs=libpython3.4m.so.1.0 -appimage - find ./jmbde -executable -type
      f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq - mv jmbde-x86_64.AppImage
      jmbde-$JMBDE_VERSION-x86_64.AppImage
    deploy:
      - provider: releases
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
        draft: true        
        api_key:
          secure: pNq/95/zTpPX25pAF3ACjoIQAnvxp6xZQYCgKhKkXhuSMCSBMl7ZIrRw0BNuM1JSHe3bRV68pfF3tgTJDWtDjFj/JHAWDOAKWhc1DeEmBXVESoizaY2Hk4yrnxjFfk+XMOFgqO+iMExap4OW+kZWXP3tltjKUYzBROMU33rey6NBiYne+UNVlzC5vgy47mj7ResrS4YBl/s3nifuE9Bigp4yDYHh4/4UgXCLXuFup+PwYRQPfwZKKiac5Bk3nHXxW+8WK3b6anboyHb+eqdZMqtu5xjqOpjwroGPPuUQsRm7c4hT93yx3IIBoIHl29hdhkWJlCOQxdhnbV0Ch9E4gombkwfHGlTFAwD3SQZFkCLdtF+1hbMgp4jta09hLgSobOIHhpGjqw+CxB5epYCM7E3WC6iKSrE7yMiSEqg6V+cf3LV+B2MlSzr1HtwLe6B7542WhFoJiF0mJCCGt//Ztp2m5174s4ZwvsiXqYMgs5x5kyp1HS5NqqllxmL3dDdPlhscKWLr7zbwDG/hhDfUpfpjefmadwf6BramK66En7fe2iol/supO86alL6/WNpCtyFaTLve/DHtWfDt+XquivGZwzCAz+0XyopJc3E7Ebxi8C49dyvdrQRi+ej1s44Cm1l/qCtS90d3WyqSfp8moepbi4pwd08vw/TD5zi8+x4=
        file: j*.AppImage
        file_glob: true
        on:
          repo: jmuelbert/jmbde-QT
          tags: true   
  - os: linux
    compiler: clang
    env:
    - QMAKESPEC=linux-clang
    - MAKEFLAGS=-j2
    before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt563-trusty
    - sudo apt-get update -qq
    - sudo apt-get -y install qt56base qt56svg qt56tools binutils zlib1g-dev cppcheck
      xvfb
    - source /opt/qt56/bin/qt56-env.sh
    - qmake -version
    script:
    - qmake
    - make
    - pushd tests/
    - qmake
    - make
    - for test in `find -executable -type f`; do pushd `dirname $test`; xvfb-run -a
      ./`basename $test`||exit 1; popd; done
    - popd
    after_script:
    - cppcheck --enable=all -q -Isrc/libtiled `git ls-files src/\*.cpp`
  - os: osx
    env:
    - INSTALLER_NAME="qt-opensource-mac-x64-clang-5.6.3"
    - QT_CI_PACKAGES="qt.563.clang_64"
    before_install:
    - brew update
    - brew install qbs
    - curl -L https://raw.githubusercontent.com/benlau/qtci/master/bin/extract-qt-installer
      --output extract-qt-installer
    - chmod +x extract-qt-installer
    - curl -L http://download.qt.io/official_releases/qt/5.6/5.6.3/${INSTALLER_NAME}.dmg
      --output ${INSTALLER_NAME}.dmg
    - hdiutil attach ${INSTALLER_NAME}.dmg
    - "./extract-qt-installer /Volumes/${INSTALLER_NAME}/${INSTALLER_NAME}.app/Contents/MacOS/${INSTALLER_NAME}
      $HOME/Qt"
    - hdiutil detach /Volumes/${INSTALLER_NAME}
    script:
    - qbs --version
    - qbs setup-toolchains --detect
    - qbs setup-qt $HOME/Qt/5.6.3/clang_64/bin/qmake qt
    - qbs config profiles.qt.baseProfile xcode-macosx-x86_64
    - qbs config defaultProfile qt
    - qbs -d build --all-products config:release
    - "$HOME/Qt/5.6.3/clang_64/bin/macdeployqt build/release/install-root/jmbde.app"
    - pushd install
    - ruby ../dist/macos/fixup-install-names.rb
    - popd
    deploy:
      - provider: releases
        skip_cleanup: true
        tag_name: "$TRAVIS_TAG"
        draft: true        
        api_key:
          secure: pNq/95/zTpPX25pAF3ACjoIQAnvxp6xZQYCgKhKkXhuSMCSBMl7ZIrRw0BNuM1JSHe3bRV68pfF3tgTJDWtDjFj/JHAWDOAKWhc1DeEmBXVESoizaY2Hk4yrnxjFfk+XMOFgqO+iMExap4OW+kZWXP3tltjKUYzBROMU33rey6NBiYne+UNVlzC5vgy47mj7ResrS4YBl/s3nifuE9Bigp4yDYHh4/4UgXCLXuFup+PwYRQPfwZKKiac5Bk3nHXxW+8WK3b6anboyHb+eqdZMqtu5xjqOpjwroGPPuUQsRm7c4hT93yx3IIBoIHl29hdhkWJlCOQxdhnbV0Ch9E4gombkwfHGlTFAwD3SQZFkCLdtF+1hbMgp4jta09hLgSobOIHhpGjqw+CxB5epYCM7E3WC6iKSrE7yMiSEqg6V+cf3LV+B2MlSzr1HtwLe6B7542WhFoJiF0mJCCGt//Ztp2m5174s4ZwvsiXqYMgs5x5kyp1HS5NqqllxmL3dDdPlhscKWLr7zbwDG/hhDfUpfpjefmadwf6BramK66En7fe2iol/supO86alL6/WNpCtyFaTLve/DHtWfDt+XquivGZwzCAz+0XyopJc3E7Ebxi8C49dyvdrQRi+ej1s44Cm1l/qCtS90d3WyqSfp8moepbi4pwd08vw/TD5zi8+x4=
        file: j*.app
        file_glob: true
        on:
          repo: jmuelbert/jmbde-QT
          tags: true
