language: cpp
sudo: required
dist: trusty
python: 3.6

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key 
    - secure:

  addons:
    coverty_scan:
      project:
        name: "jmuelbert/jmbde-QT"
        description: "A little BDE tool"
      notification_email: juergen.muelbert@gmail.com
      build_command_prepend: qmake
      build_command: make
      branch_pattern: coverity_scan

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      before_install:
        - eval "${MATRIX_EVAL}"
    - sudo add-apt-repository --yes ppa:beineri/opt-qt595-trusty
        - sudo apt-get update -qq
        - sudo apt-get -y install qt59base qt59script qt59svg qt59imageformats qt59tools binutils zlib1g-dev
        - source /opt/qt59/bin/qt59-env.sh
        - source ./tools/ci/linux/setup-qbs.sh
      script:
        - qbs --version
        - qbs setup-toolchains --detect
        - qbs setup-qt --detect
        - qbs config defaultProfile qt-5-9-5
        - qbs -d build --all-products config:release  
      after_success:
       - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" -O linuxdeployqt
        - chmod a+x linuxdeployqt
        - unset QTDIR; unset QT_PLUGIN_PATH; unset LD_LIBRARY_PATH
        - ls
        - ./linuxdeployqt ./jmbde/usr/share/applications/io.github.jmuelbert.jmbde.desktop -bundle-non-qt-libs -extra-plugins=imageformats/libqsvg.so -exclude-libs=libpython3.4m.so.1.0 -verbose=2
        - ./linuxdeployqt ./jmbde/usr/share/applications/io.github.jmuelbert.jmbde.desktop -exclude-libs=libpython3.4m.so.1.0 -appimage
        - find ./jmbde -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
        # - mv jmbde-x86_64.AppImage jmbde-$JMBDE_VERSION-x86_64.AppImage          
  deploy:
  provider: releases
  file_glob: true
  skip_cleanup: true
  on:
    repo: jmuelbert/jmbde-QT
  api_key:
    secure: qdSEjb8s9tyZPY9KChCseeJiWOEyDIyhf2GTR6CXvyqU8igyP/hqggaN/umfTTycPIrKEpdxNYuGtirRhLiPHuTW7zsyphoJwclc/eJbXHEcE8q5TEGkeSVyAatkY6wLUFZ0QpIeFl0R1P8tmzDqAkyeNGHxagRG/aWIpw6BRtjnBBd0XEFW7rxRGc7Efr05r7VKo90YUsKBMKAI78/ZFW7h1e5QhPfr/FIXLe3QZUPeAKwezYaUxQ/jrWHRC4cVTJlQIpSOJO9Ct7WhGvkIEfwzFqsZ4KZbqwyzjKlOOYnRiKwXdrfdiaRQoZjav2uiMIAZZK7dShNwCd88FZe0dE/SFtvEK3BTTkNhUXQ+xiriXaPyr505QDtkWnXtZHZEOd1J/8nJaV9K5LEjjsVyMuAzd63xS1ngc0615SAkgsS1herVpVuP95jiErbNXYZumjwrasMXnxTTruY5FGA9dme+EzHPM3t56kmTdAD+FFvS7anoew5XJze+oiveibTIxE1i9vloj4vWMEmTQ2zHzdumx+DFGGCu2Q8FHaUDyuEUV0FMiD5Rf2GdJSrr0F7m1eEdjOhh+MHL/8/+vnCiWsJulEZ3zjwMDtb8lqY0nfGtPAe7OPeAxntHs2l82cDUwX18lMz2guXT5TlMVEGnCuYLUu8DKWwdoh+G2GeG24Y=
  file: 
    - jmbde-build/src/jmbde/j*.AppImage
    - jmbde-build/src/jmbde/j*.7z

