branches:
  only:
    - master
    - prelease
    - ci/appveyor
    - appveyor

environment:

  matrix:
  - arch: x64
    qt: 6.2.4
    cc: VS2022
    mode: release
    QTDIR: C:\Qt\6.2\msvc2022_64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

 init:
  - set vcarch=%arch%
  - if "%arch%" == "x64" set vcarch=amd64
  - if %cc%==VS2022 (
      call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" %vcarch%
    ) else if not %cc%==MinGW (
      call "C:\Program Files (x86)\Microsoft Visual Studio %toolchain_version%.0\VC\vcvarsall.bat" %vcarch%
    )
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - echo QTDIR=%QTDIR%

 install:
  - git submodule update --init
  - mkdir build
  - cd build
  # - ..\tools\ci\win\install_dep.bat

before_build:
  - set PATH=%QTDIR%\bin;%PATH%
  - if %cc%==MinGW set PATH=C:\Qt\Tools\mingw%toolchain_version%_32\bin;%PATH%
  - echo PATH=%PATH%

build_script:
  # - ..\tools\ci\win\build.bat

after_build:
  # - ..\tools\ci\win\deploy_win.bat

test: off

artifacts:
  - path: 'jmbde*.7z'  # relative to repo root
