clone_depth: 200
version: 1.0.{build}

cache:
  - C:\Users\appveyor\.m2
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  my_secret:
    secure: NuyAKQY3nsfYHO6P59pRQCWMFPBYGuShNyCwrBWLuqK7jQ/CmRNZeuWuVRUvy/xU
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    QT_PROFILE: msvc2015
    QTDIR: C:\Qt\5.10.1\msvc2015
    QBS_PROFILE: MSVC2015-x86
    PUSH_RELEASE: true
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QT_PROFILE: msvc2017_64
    QTDIR: C:\Qt\5.10.1\msvc2017_64
    QBS_PROFILE: MSVC2017-x86_x64
    PUSH_RELEASE: true
# FIXME: WinRT builds are disabled due to linker issues
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    QT_PROFILE: winrt_x86_msvc2017
#    QTDIR: C:\Qt\5.10.1\winrt_x86_msvc2017
#    QBS_PROFILE: MSVC2017-x86
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    QT_PROFILE: winrt_x64_msvc2017
#    QTDIR: C:\Qt\5.10.1\winrt_x64_msvc2017
#    QBS_PROFILE: MSVC2017-x86_x64

configuration: release

init:
  - set PATH=%QTDIR%\bin;%PATH%
install:
  - choco install -y qbs --version 1.12.0
before_build:
  - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
  - set VERSION_DATE=%DATE:~10,4%.%DATE:~4,2%.%DATE:~7,2%
  - if defined APPVEYOR_REPO_TAG_NAME (set JMBDE_RELEASE=true) else (set JMBDE_SNAPSHOT=true)
  - if defined JMBDE_RELEASE set JMBDE_VERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - if defined JMBDE_RELEASE echo Building JMBDE %JMBDE_VERSION%... (from %COMMITNOW%)
  - if defined JMBDE_SNAPSHOT set JMBDE_VERSION=%APPVEYOR_BUILD_VERSION%
  - if defined JMBDE_SNAPSHOT echo Building JMBDE snapshot %JMBDE_VERSION%... (from %COMMITNOW%)  
  - qbs --version
  - qbs setup-toolchains --detect
  - qbs setup-qt %QTDIR%\bin\qmake.exe appveyor-qt5
  - qbs config profiles.appveyor-qt5.baseProfile %QBS_PROFILE%
  - qbs config defaultProfile appveyor-qt5
  - dir "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64"
  - dir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin" 
89  MSVC 2017 (x64_x86) detected in
90
build_script:
  - qbs build --all-products config:release projects.JMBde.windowsInstaller:true

after_build:
  - cd release
  - cd installer*
  - move jmbde-*.msi %APPVEYOR_BUILD_FOLDER%

  
artifacts:
  - name: Installer
    path: 'jmbde-*.msi'
  - name: Archive
    path: 'jmbde-*.7z'

deploy:
  - provider: GitHub
    release: JMBde $(JMBDE_VERSION)
    auth_token:
      secure:  NuyAKQY3nsfYHO6P59pRQCWMFPBYGuShNyCwrBWLuqK7jQ/CmRNZeuWuVRUvy/xU
    artifact: /.*\.msi/
    draft: true
    on:
      appveyor_repo_tag: true
      push_release: true    