branches:
  only:
    - master
    - prelease
    - ci/appveyor
    - appveyor

version: build-{build}

environment:
  QT_VER: 5.11.2

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: mingw53_32
    - PLATFORM: msvc2015_64
    - PLATFORM: msvc2015

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: mingw53_32
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017
    - PLATFORM: msvc2015
      image: Visual Studio 2017
    - PLATFORM: linux
      image: Ubuntu
    
install:

build_script:
  

after_build:

artifacts:
  - path: install\build_*_%QT_VER%.zip
