clone_depth: 200
version: '{branch}-{build}'

cache:
  - C:\Users\appveyor\.m2
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  my_secret:
    secure: NuyAKQY3nsfYHO6P59pRQCWMFPBYGuShNyCwrBWLuqK7jQ/CmRNZeuWuVRUvy/xU
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    QT_PROFILE: msvc2015
    QTDIR: C:\Qt\5.10.1\msvc2015
    QBS_PROFILE: MSVC2015-x86
    MY_PLATFORM: x86
    PUSH_RELEASE: true
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    QT_PROFILE: msvc2017_64
    QTDIR: C:\Qt\5.10.1\msvc2017_64
    QBS_PROFILE: MSVC2017-x86_x64
    MY_PLATFORM: x64
    PUSH_RELEASE: true
  - APP_VEYOR_BUILD_WORKER_IMAGE: Ubuntu
  
# FIXME: WinRT builds are disabled due to linker issues
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    QT_PROFILE: winrt_x86_msvc2017
#    QTDIR: C:\Qt\5.10.1\winrt_x86_msvc2017
#    QBS_PROFILE: MSVC2017-x86
#  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
#    QT_PROFILE: winrt_x64_msvc2017
#    QTDIR: C:\Qt\5.10.1\winrt_x64_msvc2017
#    QBS_PROFILE: MSVC2017-x86_x64

for:
########## UBUNTU SPECIFIC CONFIGURATION ##########
-
  matrix:
    only:
      - image: Ubuntu1804

  clone_folder: /home/appveyor/projects/mixxx

  install:
    - sudo apt-get update
    - sudo apt-get -y install gdb libavformat-dev libchromaprint-dev libfaad-dev libfftw3-dev libflac-dev libid3tag0-dev libmad0-dev libmodplug-dev libmp3lame-dev libmp4v2-dev libopusfile-dev libportmidi-dev libprotobuf-dev libqt5opengl5-dev libqt5sql5-sqlite libqt5svg5-dev librubberband-dev libshout3-dev libsndfile1-dev libsqlite3-dev libtag1-dev libupower-glib-dev libusb-1.0-0-dev libwavpack-dev portaudio19-dev protobuf-compiler qt5-default qtscript5-dev scons vamp-plugin-sdk qtkeychain-dev liblilv-dev

configuration: release

init:
  - set PATH=%QTDIR%\bin;%PATH%
install:
  - choco install -y qbs --version 1.12.0
before_build:
  - FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
  - set VERSION_DATE=%DATE:~10,4%.%DATE:~4,2%.%DATE:~7,2%
  - if defined APPVEYOR_REPO_TAG_NAME (set JMBDE_RELEASE=true) else (set JMBDE_SNAPSHOT=true)
  - if defined JMBDE_RELEASE set JMBDE_VERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - if defined JMBDE_RELEASE echo Building JMBDE %JMBDE_VERSION%... (from %COMMITNOW%)
  - if defined JMBDE_SNAPSHOT set JMBDE_VERSION=%APPVEYOR_BUILD_VERSION%
  - if defined JMBDE_SNAPSHOT echo Building JMBDE snapshot %JMBDE_VERSION%... (from %COMMITNOW%) 

  - qbs --version
  - qbs setup-toolchains --detect
  - qbs setup-qt %QTDIR%\bin\qmake.exe appveyor-qt5
  - qbs config profiles.appveyor-qt5.baseProfile %QBS_PROFILE%
  - qbs config defaultProfile appveyor-qt5

build_script:
  - qbs build config:release 
  - windeployqt release/install-root/jmbde.exe
  - qbs build --all-products config:release projects.JMBde.windowsInstaller:true

after_build:
  - cd release
  - cd install-root
  - windeployqt jmbde.exe
  - candle -ext WixUIExtension ../../dist/win/installer.wxs -dInstallRoot=. -dQtDir=%QTDIR% -dRootDir=../../ -dVersion=$JMBDE_VERSION -dPlatform=MY_PLATFORM
  - move jmbde-*.msi %APPVEYOR_BUILD_FOLDER%
  
artifacts:
  - name: Installer
    path: 'jmbde-*.msi'
  - name: Archive
    path: 'jmbde-*.7z'

deploy:
  - provider: GitHub
    release: JMBde $(JMBDE_VERSION)
    auth_token:
      secure:  NuyAKQY3nsfYHO6P59pRQCWMFPBYGuShNyCwrBWLuqK7jQ/CmRNZeuWuVRUvy/xU
    artifact: /.*\.msi/
    draft: true
    on:
      appveyor_repo_tag: true
      push_release: true    