clone_depth: 200
version: 1.0.{build}

cache:
  - C:\Users\appveyor\.m2
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml

environment:
  my_secret:
    secure: NuyAKQY3nsfYHO6P59pRQCWMFPBYGuShNyCwrBWLuqK7jQ/CmRNZeuWuVRUvy/xU
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.12.2\msvc2017_64
      PLATFORM: x64
    - GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      QTDIR: C:\Qt\5.12.2\msvc2017
      PLATFORM: x86

    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      MATRIX: "CC=gcc-7 && CXX=g++-7"


configuration: Release

init:
  - cmd: set PATH=%PATH%;%QTDIR%\bin;%WIX%\bin;
  - cmd: set VCINSTALLDIR="%ProgramFiles(x86)%\Microsoft Visual Studio\2017\BuildTools\VC"
  - sh: sudo add-apt-repository --yes ppa:beineri/opt-qt-5.12.3-bionic

install:
  # Windows
  - cmd: choco install -y qbs --version 1.12.1
  - cmd: nuget install secure-file -ExcludeVersion
  - cmd: choco install -y wixtoolset
  # Linux
  - sh: sudo apt-get update -qq
  - sh: sudo apt-get -y install binutils
  - sh: sudo apt-get -y install gcc7
  - sh: sudo apt-get -y install libgl1-mesa-dev
  - sh: sudo apt-get -y install zlib1g-dev
  - sh: eval "${MATRIX_EVAL}"
 # Qt 512
  - sh: sudo apt-get -y install qt512base 
  - sh: sudo apt-get -y install qt512script 
  - sh: sudo apt-get -y install qt512svg 
  - sh: sudo apt-get -y install qt512imageformats 
  - sh: sudo apt-get -y install qt512tools

  # Qbs 1.13
  - sh: source /opt/qt512/bin/qt512-env.sh
  - sh: source ./dist/linux/setup-qbs.sh

before_build:
  - cmd: FOR /F "tokens=*" %%i in ('git describe') do SET COMMITNOW=%%i
  - cmd: set VERSION_DATE=%DATE:~10,4%.%DATE:~4,2%.%DATE:~7,2%
  - cmd: if defined APPVEYOR_REPO_TAG_NAME (set JMBDE_RELEASE=true) else (set JMBDE_SNAPSHOT=true)
  - cmd: if defined JMBDE_RELEASE set JMBDE_VERSION=%APPVEYOR_REPO_TAG_NAME:~1%
  - cmd: if defined JMBDE_RELEASE echo Building JMBDE %JMBDE_VERSION%... (from %COMMITNOW%)
  - cmd: if defined JMBDE_SNAPSHOT set JMBDE_VERSION=%APPVEYOR_BUILD_VERSION%
  - cmd: if defined JMBDE_SNAPSHOT echo Building JMBDE snapshot %JMBDE_VERSION%... (from %COMMITNOW%)

  - qbs --version
  - qbs setup-toolchains --detect
  - cmd: qbs setup-qt %QTDIR%\bin\qmake.exe qt
  - cmd: qbs config defaultProfile qt
  - sh: qbs config defaultProfile gcc
  - sh: qbs setup-qt /opt/qt512/bin/qmake qt512
  - sh: qbs config defaultProfile qt512

build_script:
  - qbs build --all-products config:release
  - sh: qbs install --install-root jmbde config:release qbs.installPrefix:/usr projects.JMBde.version:$JMBDE_VERSION

after_build:
  - cmd: cd Release\install-root 
  # https://aka.ms/vs/16/release/VC_redist.x64.exe
  - cmd: windeployqt jmbde.exe
  - cmd: candle.exe -arch %PLATFORM% -ext WixUIExtension -ext WixUtilExtension ../../dist/win/vcredist_%PLATFORM%.wxs -dInstallRoot=.  -dQtDir=%QTDIR%
  - cmd: candle.exe -arch %PLATFORM% -ext WixUIExtension -ext WixUtilExtension ../../dist/win/installer.wxs  -dInstallRoot=. -dQtDir=%QTDIR% -dRootDir=../../ -dVersion=%JMBDE_VERSION% -dPlatform=%PLATFORM%
  - cmd: light.exe -ext WixUIExtension -ext WixUtilExtension installer.wixobj -out jmbde-%JMBDE_VERSION%-win_%MY_PLATFORM%.msi
  - cmd: move jmbde-*.msi %APPVEYOR_BUILD_FOLDER%
  - sh: cp LICENSE* *md jmbde/

# vcredist_%PLATFORM%.wixobj

artifacts:
  - name: Installer
    path: "jmbde-*.msi"
  - name: Archive
    path: "jmbde-*.7z"

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    auth_token:
      secure: NuyAKQY3nsfYHO6P59pRQCWMFPBYGuShNyCwrBWLuqK7jQ/CmRNZeuWuVRUvy/xU
    artifact: /.*\.msi/
    draft: true
    on:
      appveyor_repo_tag: true
      push_release: true
