branches:
  only:
    - master
    - prelease
    - ci/appveyor
    - appveyor

image:
  - Visual Studio 2017
  - Visual Studio 2015

version: build-{build}

environment:
  QT_VER: 5.11.2
  EXTRA_MODULES: .skycoder42

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: winrt_x64_msvc2017
    - PLATFORM: winrt_x86_msvc2017
    - PLATFORM: winrt_armv7_msvc2017
    - PLATFORM: msvc2015_64
    - PLATFORM: msvc2015
    - PLATFORM: mingw53_32
    # only when using static tools
    - PLATFORM: static

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: winrt_x64_msvc2017
      image: Visual Studio 2015
    - PLATFORM: winrt_x86_msvc2017
      image: Visual Studio 2015
    - PLATFORM: winrt_armv7_msvc2017
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017
    - PLATFORM: msvc2015
      image: Visual Studio 2017
    - PLATFORM: mingw53_32
      image: Visual Studio 2017
    - PLATFORM: static
      image: Visual Studio 2015

    
install:
  - .\tools\ci\win\setup.bat

build_script:
  - .\tools\ci\win\build.bat

after_build:
  - .\tools\ci\win\upload-prepare.bat

artifacts:
  - dir
  - path: install\build_*_%QT_VER%.zip
