branches:
  only:
    - master
    - prelease
    - ci/appveyor
    - appveyor

version: build-{build}

environment:
  QT_VER: 5.11.2

  matrix:
    - PLATFORM: msvc2017_64
    - PLATFORM: mingw53_32
    - PLATFORM: msvc2015_64
    - PLATFORM: msvc2015

matrix:
  exclude:
    - PLATFORM: msvc2017_64
      image: Visual Studio 2015
    - PLATFORM: mingw53_32
      image: Visual Studio 2015
    - PLATFORM: msvc2015_64
      image: Visual Studio 2017
    - PLATFORM: msvc2015
      image: Visual Studio 2017

install:
  - git clone https://github.com/Skycoder42/QtModules.git .\qtmodules-travis
  - .\qtmodules-travis\ci\win\setup.bat

build_script:
  - .\qtmodules-travis\ci\win\build.bat

after_build:
  - .\qtmodules-travis\ci\win\upload-prepare.bat

artifacts:
  - path: install\build_*_%QT_VER%.zip
