version: 2
jobs:
  build:
    docker:
     # Primary container image where all steps run.
     - image: buildpack-deps:trusty
    # Secondary container image on common network. 
     - image: mongo:2.6.8-jessie
       command: [mongod, --smallfiles]

    working_directory: ~/

    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - run: sleep 5 && nc -vz localhost 27017


  build:
      macos:
        xcode: "9.0"
      
      steps:
        # Commands will execute in macOS container
        # with Xcode 9.0 installed
        - run: xcodebuild -version
  test:
    docker:
    # Primary container image where all steps run.
     - image: buildpack-deps:trusty
    # Secondary container image on common network. 
     - image: mongo:2.6.8-jessie
       command: [mongod, --smallfiles
    steps:
      - checkout
      - run: <command>
  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test
        
machine:
  services:
    - docker
  timezone:
    Europe/Berlin
  environment:
    MAKEFLAGS: "j4"
    BUILD__: "x86_64"
    BTYPE__: "release"
dependencies:
  cache_directories:
    - "~/cache"
  pre:
    - sudo apt-get update
    - sudo apt-get install zip
    - docker info
    - ./.travis/build-windows.sh "$BUILD__" "$BTYPE__" ~/cache/"$BUILD__" stage1
    - ./.travis/build-windows.sh "$BUILD__" "$BTYPE__" ~/cache/"$BUILD__" stage2
    - ls -al ~/cache
compile:
  override:
    - ./.travis/build-windows.sh "$BUILD__" "$BTYPE__" ~/cache/"$BUILD__" stage3
    - ls -al ~/

    - ls -al /home/ubuntu/jmbde/workspace/"$BUILD__"/jmbde/"$BTYPE__"/
    - ls -al /home/ubuntu/jmbde/workspace/"$BUILD__"/jmbde/"$BTYPE__"/jmbde.exe
    
    - mkdir -p $CIRCLE_ARTIFACTS/"$BUILD__"/
    - cp -av /home/ubuntu/jmbde/workspace/"$BUILD__"/jmbde/"$BTYPE__"/jmbde.exe $CIRCLE_ARTIFACTS/"$BUILD__"/jmbde_"$BTYPE__".exe
    - cd /home/ubuntu/jmbde/workspace/"$BUILD__"/jmbde/"$BTYPE__"/ ; zip -r $CIRCLE_ARTIFACTS/"$BUILD__"/jmbde_"$BUILD__"_"$BTYPE__".zip *
    - echo "Download Artifacts for this PR at https://circleci.com/api/v2/project/jmbde/jmbde/latest/artifacts/0/\$CIRCLE_ARTIFACTS/x86_64/jmbde_x86_64_release.zip?filter=completed&branch=$CIRCLE_BRANCH"
test:
  override:
    - "true"