#if !defined(CONFIG_APPLICATION_H)
#define CONFIG_APPLICATION_H

#cmakedefine APPLICATION_INSTALL_QT_LAYOUT
#define APPLICATION_DEBUG_POSTFIX "${CMAKE_DEBUG_POSTFIX}"

// relative install dirs
#define APPLICATION_PLUGIN_INSTALL_DIR "${PLUGIN_INSTALL_DIR}"
#define APPLICATION_LIBEXEC_INSTALL_DIR "${LIBEXEC_INSTALL_DIR}"
#define APPLICATION_BUNDLE_INSTALL_DIR "${BUNDLE_INSTALL_DIR_PRIVATE}"
#define APPLICATION_BIN_INSTALL_DIR "${BIN_INSTALL_DIR}"
#define APPLICATION_PROBE_INSTALL_DIR "${PROBE_INSTALL_DIR}"
#define APPLICATION_TRANSLATION_INSTALL_DIR "${TRANSLATION_INSTALL_DIR}"
#define APPLICATION_QCH_INSTALL_DIR "${QCH_INSTALL_DIR}"
#define APPLICATION_TARGET_PLUGIN_INSTALL_DIR "${TARGET_PLUGIN_INSTALL_DIR}"

#define APPLICATION_PLUGIN_VERSION "${APPLICATION_PLUGIN_VERSION}"
#define APPLICATION_PROBE_ABI "${APPLICATION_PROBE_ABI}${APPLICATION_PROBE_ABI_POSTFIX}"

// relative inverse install dirs
#define APPLICATION_INVERSE_BUNDLE_DIR "${APPLICATION_INVERSE_BUNDLE_DIR}"
#define APPLICATION_INVERSE_BIN_DIR "${APPLICATION_INVERSE_BIN_DIR}"
#define APPLICATION_INVERSE_LIB_DIR "${APPLICATION_INVERSE_LIB_DIR}"
#define APPLICATION_INVERSE_PROBE_DIR "${APPLICATION_INVERSE_PROBE_DIR}"
#define APPLICATION_INVERSE_LIBEXEC_DIR "${APPLICATION_INVERSE_LIBEXEC_DIR}"

// probe name
#define APPLICATION_PROBE_BASENAME "${PROBE_BASENAME}"

// default network properties
#define APPLICATION_DEFAULT_LOCAL_ADDRESS "127.0.0.1"
#define APPLICATION_DEFAULT_LOCAL_TCP_URL "tcp://127.0.0.1"
#define APPLICATION_DEFAULT_ANY_ADDRESS "0.0.0.0"
#define APPLICATION_DEFAULT_ANY_TCP_URL "tcp://0.0.0.0"

// build options
#cmakedefine HAVE_STDINT_H
#cmakedefine HAVE_BACKTRACE
#cmakedefine HAVE_CXA_DEMANGLE

#cmakedefine HAVE_QT_WIDGETS
#cmakedefine HAVE_QT_SCXML
#cmakedefine HAVE_QT_SVG
#cmakedefine HAVE_QT_DESIGNER
#cmakedefine HAVE_QT_PRINTSUPPORT

#cmakedefine HAVE_SYNTAX_HIGHLIGHTING

#cmakedefine HAVE_ELF_H
#cmakedefine HAVE_SYS_ELF_H
#cmakedefine HAVE_ELF

#cmakedefine APPLICATION_ENABLE_GPL_ONLY_FEATURES
#cmakedefine APPLICATION_CORE_ONLY_LAUNCHER
#cmakedefine APPLICATION_STATIC_PROBE
#cmakedefine APPLICATION_DISABLE_FEEDBACK

#cmakedefine APPLICATION_WITH_WIDGET3D

#define QT_LIBINFIX "@QT_LIBINFIX@"

#endif // CONFIG_APPLICATION_H
