#ifndef CONFIG_APPLICATION_VERSION_H
#define CONFIG_APPLICATION_VERSION_H

#define APPLICATION_VERSION_MAJOR ${APPLICATION_VERSION_MAJOR}
#define APPLICATION_VERSION_MINOR ${APPLICATION_VERSION_MINOR}
#define APPLICATION_VERSION_PATCH ${APPLICATION_VERSION_PATCH}
#define APPLICATION_VERSION_STRING "${APPLICATION_VERSION_STRING}"
#define APPLICATION_COMPACT_VERSION_STRING "${APPLICATION_VERSION_MAJOR}.${APPLICATION_VERSION_MINOR}.${APPLICATION_VERSION_PATCH}"

#endif