project_identifier: jmbde-qt
api_key: 87e89bbe696340b8616533b6d62cf374
base_path: /translations
preserve_hierarchy: true
files:
  - source: /translations/de/*.ts
    translation: /translations/%two_letters_code%/%original_file_name%
