version: '0.2'
language: en,de-DE,it,es-ES
ignorePaths:
  - '**/node_modules/**'
  - '**/vscode_extension/**'
  - '**/.git/**'
  - '**/pnpm-lock.yaml'
  - '**/package-lock.json'
  - '**/yarn.lock'
  - '**/tsconfig.json'
  - dist/
  - out/
  - build/
  - .vscode
  - package-lock.json
  - megalinter-reports
  - .devcontainer/.dockerignore
  - .git*
  - .prettierignore
  - .codespellrc
  - CHANGELOG.md
  - LICENSE
  - license.txt
  - '**/{report,site,LICENSES,docs/about/EUPL-1.2.md}/**'
  - cspell.config.yaml
  - '**/styles/vale/**'
  - '**/nbproject/**'
words:
  - jmuelbert
  - Jürgen
  - juergen
  - Mülbert
  - muelbert
  - apdisk
  - donotpresent
  - ehthumbs
  - esktop
  - fseventsd
  - HSTS
  - icns
  - msix
  - NOLOGO
  - nupkg
  - rarr
  - 
maxNumberOfProblems: 1000
import: []
useGitignore: true
overrides:
  - filename: '**/de_DE/**'
    language: en,de
  - filename: '**/nl_NL/**'
    language: en,nl
  - filename: '**/ru_RU/samples/**'
    language: ru,en
  - filename: '**/sv/**'
    language: en,sv
  - filename: package.json
    ignoreWords:
      - color
      - cannot
  - filename: pyproject.toml
    ignoreWords:
      - LICENSE
  - filename: LICENSE
    ignoreWords:
      - LICENCE
      - authorised
      - Unported
allowCompoundWords: true
enableGlobDot: true
cache:
  useCache: true
  cacheStrategy: content
enableFiletypes:
  - shellscript
dictionaryDefinitions:
  - name: project-words
    addWords: true
    scope:
      - workspace
    path: ./.github/styles/config/vocabularies/cspell/project-words.txt
  - name: local-german
    addWords: true
    scope:
      - workspace
    path: ./.github/styles/config/vocabularies/cspell/german-words.txt
  - name: local-spanish
    addWords: true
    scope:
      - workspace
    path: ./.github/styles/config/vocabularies/cspell/spanish-words.txt
  - name: local-italiano
    addWords: true
    scope:
      - workspace
    path: ./.github/styles/config/vocabularies/cspell/italian-words.txt
  - name: local-ruby
    addWords: false
    scope:
      - workspace
    path: ./.github/styles/config/vocabularies/cspell/ruby-words.txt
  - name: local-python
    addWords: false
    scope:
      - workspace
    path: ./.github/styles/config/vocabularies/cspell/python-words.txt
  - name: local-github-actions
    addWords: false
    scope:
      - workspace
    path: ./.github/styles/config/vocabularies/cspell/github-actions.txt
  - name: local-node
    addWords: false
    scope:
      - workspace
    path: ./.github/styles/config/vocabularies/cspell/node.txt
dictionaries:
  - project-words
  - local-german
  - local-spanish
  - local-italiano
  - local-ruby
  - local-python
  - local-github-actions
  - local-node
  - bash
  - companies
  - csharp
  - css
  - filetypes
  - fonts
  - misc
  - node
  - npm
  - powershell
  - python
  - software-terms
  - typescript
