

function(conan_message MESSAGE_OUTPUT)
    if(NOT CONAN_CMAKE_SILENT_OUTPUT)
        message(${ARGV${0}})
    endif()
endfunction()


macro(conan_find_apple_frameworks FRAMEWORKS_FOUND FRAMEWORKS FRAMEWORKS_DIRS)
    if(APPLE)
        foreach(_FRAMEWORK ${FRAMEWORKS})
            # https://cmake.org/pipermail/cmake-developers/2017-August/030199.html
            find_library(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND NAME ${_FRAMEWORK} PATHS ${FRAMEWORKS_DIRS} CMAKE_FIND_ROOT_PATH_BOTH)
            if(CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND)
                list(APPEND ${FRAMEWORKS_FOUND} ${CONAN_FRAMEWORK_${_FRAMEWORK}_FOUND})
            else()
                message(FATAL_ERROR "Framework library ${_FRAMEWORK} not found in paths: ${FRAMEWORKS_DIRS}")
            endif()
        endforeach()
    endif()
endmacro()


function(conan_package_library_targets libraries package_libdir deps out_libraries out_libraries_target build_type package_name)
    unset(_CONAN_ACTUAL_TARGETS CACHE)
    unset(_CONAN_FOUND_SYSTEM_LIBS CACHE)
    foreach(_LIBRARY_NAME ${libraries})
        find_library(CONAN_FOUND_LIBRARY NAME ${_LIBRARY_NAME} PATHS ${package_libdir}
                     NO_DEFAULT_PATH NO_CMAKE_FIND_ROOT_PATH)
        if(CONAN_FOUND_LIBRARY)
            conan_message(STATUS "Library ${_LIBRARY_NAME} found ${CONAN_FOUND_LIBRARY}")
            list(APPEND _out_libraries ${CONAN_FOUND_LIBRARY})
            if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
                # Create a micro-target for each lib/a found
                set(_LIB_NAME CONAN_LIB::${package_name}_${_LIBRARY_NAME}${build_type})
                if(NOT TARGET ${_LIB_NAME})
                    # Create a micro-target for each lib/a found
                    add_library(${_LIB_NAME} UNKNOWN IMPORTED)
                    set_target_properties(${_LIB_NAME} PROPERTIES IMPORTED_LOCATION ${CONAN_FOUND_LIBRARY})
                    set(_CONAN_ACTUAL_TARGETS ${_CONAN_ACTUAL_TARGETS} ${_LIB_NAME})
                else()
                    conan_message(STATUS "Skipping already existing target: ${_LIB_NAME}")
                endif()
                list(APPEND _out_libraries_target ${_LIB_NAME})
            endif()
            conan_message(STATUS "Found: ${CONAN_FOUND_LIBRARY}")
        else()
            conan_message(STATUS "Library ${_LIBRARY_NAME} not found in package, might be system one")
            list(APPEND _out_libraries_target ${_LIBRARY_NAME})
            list(APPEND _out_libraries ${_LIBRARY_NAME})
            set(_CONAN_FOUND_SYSTEM_LIBS "${_CONAN_FOUND_SYSTEM_LIBS};${_LIBRARY_NAME}")
        endif()
        unset(CONAN_FOUND_LIBRARY CACHE)
    endforeach()

    if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
        # Add all dependencies to all targets
        string(REPLACE " " ";" deps_list "${deps}")
        foreach(_CONAN_ACTUAL_TARGET ${_CONAN_ACTUAL_TARGETS})
            set_property(TARGET ${_CONAN_ACTUAL_TARGET} PROPERTY INTERFACE_LINK_LIBRARIES "${_CONAN_FOUND_SYSTEM_LIBS};${deps_list}")
        endforeach()
    endif()

    set(${out_libraries} ${_out_libraries} PARENT_SCOPE)
    set(${out_libraries_target} ${_out_libraries_target} PARENT_SCOPE)
endfunction()


include(FindPackageHandleStandardArgs)

conan_message(STATUS "Conan: Using autogenerated Findcmake.cmake")
# Global approach
set(cmake_FOUND 1)
set(cmake_VERSION "3.19.6")

find_package_handle_standard_args(cmake REQUIRED_VARS
                                  cmake_VERSION VERSION_VAR cmake_VERSION)
mark_as_advanced(cmake_FOUND cmake_VERSION)


set(cmake_INCLUDE_DIRS )
set(cmake_INCLUDE_DIR "")
set(cmake_INCLUDES )
set(cmake_RES_DIRS )
set(cmake_DEFINITIONS )
set(cmake_LINKER_FLAGS_LIST
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,SHARED_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,MODULE_LIBRARY>:>"
        "$<$<STREQUAL:$<TARGET_PROPERTY:TYPE>,EXECUTABLE>:>"
)
set(cmake_COMPILE_DEFINITIONS )
set(cmake_COMPILE_OPTIONS_LIST "" "")
set(cmake_COMPILE_OPTIONS_C "")
set(cmake_COMPILE_OPTIONS_CXX "")
set(cmake_LIBRARIES_TARGETS "") # Will be filled later, if CMake 3
set(cmake_LIBRARIES "") # Will be filled later
set(cmake_LIBS "") # Same as cmake_LIBRARIES
set(cmake_SYSTEM_LIBS )
set(cmake_FRAMEWORK_DIRS )
set(cmake_FRAMEWORKS )
set(cmake_FRAMEWORKS_FOUND "") # Will be filled later
set(cmake_BUILD_MODULES_PATHS )

conan_find_apple_frameworks(cmake_FRAMEWORKS_FOUND "${cmake_FRAMEWORKS}" "${cmake_FRAMEWORK_DIRS}")

mark_as_advanced(cmake_INCLUDE_DIRS
                 cmake_INCLUDE_DIR
                 cmake_INCLUDES
                 cmake_DEFINITIONS
                 cmake_LINKER_FLAGS_LIST
                 cmake_COMPILE_DEFINITIONS
                 cmake_COMPILE_OPTIONS_LIST
                 cmake_LIBRARIES
                 cmake_LIBS
                 cmake_LIBRARIES_TARGETS)

# Find the real .lib/.a and add them to cmake_LIBS and cmake_LIBRARY_LIST
set(cmake_LIBRARY_LIST )
set(cmake_LIB_DIRS )

# Gather all the libraries that should be linked to the targets (do not touch existing variables):
set(_cmake_DEPENDENCIES "${cmake_FRAMEWORKS_FOUND} ${cmake_SYSTEM_LIBS} OpenSSL::OpenSSL")

conan_package_library_targets("${cmake_LIBRARY_LIST}"  # libraries
                              "${cmake_LIB_DIRS}"      # package_libdir
                              "${_cmake_DEPENDENCIES}"  # deps
                              cmake_LIBRARIES            # out_libraries
                              cmake_LIBRARIES_TARGETS    # out_libraries_targets
                              ""                          # build_type
                              "cmake")                                      # package_name

set(cmake_LIBS ${cmake_LIBRARIES})

foreach(_FRAMEWORK ${cmake_FRAMEWORKS_FOUND})
    list(APPEND cmake_LIBRARIES_TARGETS ${_FRAMEWORK})
    list(APPEND cmake_LIBRARIES ${_FRAMEWORK})
endforeach()

foreach(_SYSTEM_LIB ${cmake_SYSTEM_LIBS})
    list(APPEND cmake_LIBRARIES_TARGETS ${_SYSTEM_LIB})
    list(APPEND cmake_LIBRARIES ${_SYSTEM_LIB})
endforeach()

# We need to add our requirements too
set(cmake_LIBRARIES_TARGETS "${cmake_LIBRARIES_TARGETS};OpenSSL::OpenSSL")
set(cmake_LIBRARIES "${cmake_LIBRARIES};OpenSSL::OpenSSL")

set(CMAKE_MODULE_PATH "/Users/juergen/.conan/data/cmake/3.19.6/_/_/package/cf36af68367ac960cc1360ef3ea3c735fa475414/" ${CMAKE_MODULE_PATH})
set(CMAKE_PREFIX_PATH "/Users/juergen/.conan/data/cmake/3.19.6/_/_/package/cf36af68367ac960cc1360ef3ea3c735fa475414/" ${CMAKE_PREFIX_PATH})

if(NOT ${CMAKE_VERSION} VERSION_LESS "3.0")
    # Target approach
    if(NOT TARGET cmake::cmake)
        add_library(cmake::cmake INTERFACE IMPORTED)
        if(cmake_INCLUDE_DIRS)
            set_target_properties(cmake::cmake PROPERTIES INTERFACE_INCLUDE_DIRECTORIES
                                  "${cmake_INCLUDE_DIRS}")
        endif()
        set_property(TARGET cmake::cmake PROPERTY INTERFACE_LINK_LIBRARIES
                     "${cmake_LIBRARIES_TARGETS};${cmake_LINKER_FLAGS_LIST}")
        set_property(TARGET cmake::cmake PROPERTY INTERFACE_COMPILE_DEFINITIONS
                     ${cmake_COMPILE_DEFINITIONS})
        set_property(TARGET cmake::cmake PROPERTY INTERFACE_COMPILE_OPTIONS
                     "${cmake_COMPILE_OPTIONS_LIST}")
        
        # Library dependencies
        include(CMakeFindDependencyMacro)

        if(NOT OpenSSL_FOUND)
            find_dependency(OpenSSL REQUIRED)
        else()
            message(STATUS "Dependency OpenSSL already found")
        endif()

    endif()
endif()

foreach(_BUILD_MODULE_PATH ${cmake_BUILD_MODULES_PATHS})
    include(${_BUILD_MODULE_PATH})
endforeach()
