# Due to rate limiting from gnu.org
accept = [429]

cache = true
exclude = ['^https://flatpak\.org']
exclude_path = [
  ".cache/",
  ".direnv/",
  ".flatpak/",
  ".flatpak-builder/",
  "build.*/",
  "repo/",
]
max_cache_age = "2w"
