#!/bin/bash

BUILDROOT="$(pwd)/tmp-buildroot/"
rm -rf "$BUILDROOT"
[ -d buildroot ] || mkdir -p "${BUILDROOT}"/{SOURCES,SPECS}

pushd "$(git rev-parse --show-toplevel)" || exit
VERSION="$(git describe | sed 's/^v//' | sed 's/-[^-]*$//' | sed 's/-/\./')"
git archive HEAD --prefix=jmbde-"$VERSION"/ -o "${BUILDROOT}"/SOURCES/jmbde-"$VERSION".tar.gz || exit 1
popd || exit

sed <jmbde.spec "s/^Version:\(.*\)/Version: $VERSION/" >"${BUILDROOT}"/SPECS/jmbde_tmp.spec

rpmbuild --define "_topdir ${BUILDROOT}/" -bs "${BUILDROOT}"/SPECS/jmbde_tmp.spec || exit 1

pushd "${BUILDROOT}" || exit
FILE=$(find . -name "*.src.rpm")
cp "$FILE" ../jmbde.src.rpm
popd || exit
rm -rf "$BUILDROOT"

if [ "$1" = "srpm-only" ]; then
	echo "Wrote jmbde.src.rpm. Exiting."
else
	COPR_CONFIG="
[copr-cli]
login = $1
username = $2
token = $3
copr_url = https://copr.fedorainfracloud.org
"
	copr --config <(echo "$COPR_CONFIG") build ablu/jmbde-dailies jmbde.src.rpm || exit 1

	rm jmbde.src.rpm
fi
