version: 3

tasks:
  gcc:
    - docker-compose up --build build-gcc
    - docker-compose up --build test-gcc
    - docker-compose down

  gcc.custom-linker:
    - docker-compose up --build build-gcc-with-custom-linker
    - docker-compose down

  llvm:
    - docker-compose up --build build-llvm
    - docker-compose up --build test-llvm
    - docker-compose down

  mingw:
    - docker-compose up --build minimal-build-mingw-x64
    - docker-compose up --build minimal-build-mingw-x64-from-env
    - docker-compose up --build minimal-build-mingw-x64-from-triplet
    - docker-compose up --build minimal-build-mingw-x86
    - docker-compose down

  emscripten:
    - docker-compose up --build build-emscripten
    - docker-compose down

  rpi3:
    - docker-compose up --build build-rpi3
    - docker-compose down

  rpi3.debug:
    - docker-compose up --build build-rpi3-debug
    - docker-compose down

  rpi3.bare-metal:
    - docker-compose up --build build-rpi3-bare-metal
    - docker-compose down

  rpi4:
    - docker-compose up --build build-rpi4
    - docker-compose down

  rpi4.debug:
    - docker-compose up --build build-rpi4-debug
    - docker-compose down

  rpi4.test:
    - docker-compose up --build test-rpi4
    - docker-compose down

  rpi4.custom:
    - docker-compose up --build build-rpi4-custom
    - docker-compose down

  rpi4.aarch64:
    - docker-compose up --build build-rpi4-aarch64
    - docker-compose down

  rpi4.vcpkg:
    - docker-compose up --build build-rpi4-vcpkg
    - docker-compose down

  rpi4.vcpkg-custom:
    - docker-compose up --build build-rpi4-vcpkg-custom
    - docker-compose down
