=head1 NAME

jmbde - A real-time realistic planetarium

=head1 SYNOPSIS

jmbde [B<OPTIONS>]

=head1 DESCRIPTION

jmbde is a free GPL software which renders realistic skies in real
time with OpenGL. It is available for Linux/Unix, Windows and MacOSX.
With jmbde, you really see what you can see with your eyes,
binoculars or a small telescope.

=head1 OPTIONS

=over

=item B<-v, --version>

Print program name and version and exit.

=item B<-h, --help>

Print a brief synopsis of program options and exit.

=head1 NOTES

Sources of more information:

=over

=item Websites

Main website: L<http://github.com/jmuelbert/jmbde/>

Downloads: L<http://github.com/jmuelbert/jmbde/>

Support Requests: L<http://github.com/jmuelbert/jmbde>

Bug Tracker: L<http://github.com/jmuelbert/jmbde>

=item The jmbde User Guide

Visit the downloads page to get a PDF copy of the jmbde User Guide.

=back

=head1 BUGS

Please report bugs using the bug tracker link in the NOTES section
of this page.

=head1 AUTHOR

Jürgen Mülbert

x14817

=cut
