#!/bin/sh
export LD_LIBRARY_PATH=/usr/lib/jmbde:$LD_LIBRARY_PATH
export QT_PLUGIN_PATH=/usr/share/jmbde/plugins/:$QT_PLUGIN_PATH
export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/share/jmbde/plugins/platforms:$QT_QPA_PLATFORM_PLUGIN_PATH

"/usr/share/jmbde/bin/jmbde" "$@"
