#!/bin/sh

export Qt6_Dir=$(brew --prefix qt)
BUILD_TYPE=Release
MAC_OS_TARGET=12.0

pip install conan

rm -rf build/"$BUILD_TYPE"

conan profile detect --force
conan install . --build=missing --settings=build_type="$BUILD_TYPE"

cmake -S . -B build/"$BUILD_TYPE" \
  -DQT_DEBUG_FIND_PACKAGE=ON \
  -DCMAKE_TOOLCHAIN_FILE=generators/conan_toolchain.cmake \
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
  -DCMAKE_OSX_DEPLOYMENT_TARGET="$MAC_OS_TARGET" \
  -DCMAKE_INSTALL_PREFIX:PATH=./app

# Execute the build.  You can specify a specific target with "--target <NAME>"

cmake --build build/"$BUILD_TYPE" \
  --config "$BUILD_TYPE" \
  --target install \
  --parallel "$(sysctl -n hw.logicalcpu)"

cd build || exit
ctest -VV
cpack -G 7Z
cpack -G STGZ
cpack -G TBZ2
cpack -G TGZ
cpack -G TXZ
# cpack -G TZ
cpack -G TZST
cpack -G ZIP
cpack -G IFW
cpack -G DragNDrop
cp jmbdeqt-0.7.0.-macos_x86_64.dmg jmbdeqt-0.7.0-dnd-macos_x86_64.dmg
cpack -G IFW
