#!/bin/sh

# rm -rf build_ubuntu
# mkdir -p build_ubuntu
cd build_ubuntu
cmake -G "Ninja" \
	-DCMAKE_BUILD_TYPE="RelWithDebInfo" \
	-DCMAKE_INSTALL_PREFIX:PATH="./install" \
	-DBUILD_EXECUTABLE="ON" \
	-DBUILD_SHARED_LIBS="ON" \
	-DBUILD_TRANSLATIONS="ON" \
	-DENABLE_APP_AUTO_DEPLOY="ON" \
	-DENABLE_DOXYGEN="ON" \
	-DENABLE_TESTING="ON" \
	-DENABLE_CCACHE="ON" \
	-S .. -B .

cmake --build . --target package
ctest -VV
cpack -G 7Z
cpack -G STGZ
cpack -G TBZ2
cpack -G TGZ
cpack -G TXZ
cpack -G TZ
cpack -G TZST
cpack -G ZIP
cpack -G IFW
cpack -G DEB
cpack -G RPM
