#!/bin/bash

if [[ $1 == 'r' ]]; then
    LOCATIONS=relative
elif [[ $1 == 'a' ]]; then
    LOCATIONS=absolute
else
    LOCATIONS=none
fi

SOURCES=(src build/src/app build/src/libs/models/jmbdemodels_autogen build/src/libs/quick/jmbdequick_autogen build/src/libs/widgets/jmbde_widgets_autogen)

for i in zh_CN ru_RU; do
    lupdate -no-obsolete "${SOURCES[@]}" -locations "$LOCATIONS" -tr-function-alias tr+=TRKEY -ts translations/$i.ts
done
