---
name: jmbde
version: '0.5.4'
base: core20
summary: A BDE tool.
description: |
    jmbde is a free bde tool.
grade: stable
confinement: strict

apps:
    jmbde:
        command: desktop-launch ${SNAP}/usr/bin/jmbde
        environment:
            QT_QPA_PLATFORMTHEME: gtk3
        plugs:
            - home
            - x11
            - wayland
            - opengl
            - network
            - network-bind
            - unity7
            - pulseaudio
            - desktop
            - desktop-legacy
            - gsettings
            - network-control
            - network-manager
        common-id: com.github.jmuelbert.jmbde-QT
        desktop: usr/share/applications/com.github.jmuelbet/jmbde.desktop

parts:
    jmbde:
        plugin: cmake
        source-type: git
        source: .
        qt-version: qt5
        parse-info: [usr/share/metainfo/jmbde.metainfo.xml]
        build-packages:
            - build-essential
            - qttools5-dev
            - qt5-default
            - libgrpc++-dev
            - libprotobuf-dev
            - protobuf-compiler-grpc
            - pkg-config
            - libzxingcore-dev
        stage-packages:
            - libgcc1
            - libstdc++6
            - libssl1.1
            - libgrpc++1
            - libprotobuf17
            - libqt5core5a
            - libqt5gui5
            - libqt5network5
            - libqt5widgets5
            - libglib2.0-bin
            - libzxingcore1
        cmake-parameters:
            - -DCMAKE_INSTALL_PREFIX=/usr
            - -DCMAKE_BUILD_TYPE=Release
            - -DEMBED_TRANSLATIONS=ON
        override-pull: |
            snapcraftctl pull
            build_number=$(cat makespec/BUILDVERSION)
            tag=$(cat makespec/VERSION)
            version=$tag.$build_number
            snapcraftctl set-version "$version"
            sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/1024x1024/apps/jmbde.png|g' packaging/linux/jmbde.desktop
        after:
            - desktop-qt5

    desktop-qt5:
        source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
        source-subdir: qt
        plugin: make
        make-parameters: [FLAVOR=qt5]
        build-packages:
            - build-essential
            - qtbase5-dev
            - dpkg-dev
        stage-packages:
            - libxkbcommon0
            - ttf-ubuntu-font-family
            - dmz-cursor-theme
            - light-themes
            - adwaita-icon-theme
            - gnome-themes-standard
            - shared-mime-info
            - libqt5gui5
            - libgdk-pixbuf2.0-0
            - libqt5svg5 # for loading icon themes which are svg
            - try: [appmenu-qt5] # not available on core18
            - locales-all
            - xdg-user-dirs
            - fcitx-frontend-qt5

    qt5-gtk-platform:
        plugin: nil
        stage-packages:
            - qt5-gtk-platformtheme
