---
name: jmbde-qt
summary: A BDE tool.
description: jmbde is a free bde tool.
adopt-info: jmbde-qt
grade: stable
confinement: strict
base: core20
version: '0.5.4'
icon: assets/icons/jmbde.png

parts:
    jmbde-qt:
        plugin: cmake
        source-type: git
        source: .
        build-packages:
            - build-essential
            - g++
            - make
            - cmake
            - qttools5-dev
            - pkg-config
            - libtsvg5-dev
        stage-packages:
            - qt5-default
            - libqt5svg5-dev

        cmake-parameters:
            - -DCMAKE_INSTALL_PREFIX=/usr
            - -DCMAKE_BUILD_TYPE=Release
            - -DEMBED_TRANSLATIONS=ON
        override-pull: |
            snapcraftctl pull
            snapcraftctl set-version "$(git describe --tags --abbrev=0)"
        override-build: |
            snapcraftctl build
            sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/res/app/jmbde-qt.desktop
            mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
            cp -rf ${SNAPCRAFT_PART_SRC}/res/app/spotify-qt.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/jmbde-qt.desktop
        after: [desktop-qt5]
        # Snapcraft Qt5 desktop launcher
        desktop-qt5:
            source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
            source-subdir: qt
            plugin: make
            make-parameters: ["FLAVOR=qt5"]
            build-packages:
                - build-essential
                - qtbase5-dev
                - dpkg-dev
            stage-packages:
                - libxkbcommon0
                - ttf-ubuntu-font-family
                - dmz-cursor-theme
                - light-themes
                - adwaita-icon-theme
                - gnome-themes-standard
                - shared-mime-info
                - libgcc1
                - libstdc++6
                - libgdk-pixbuf2.0-0
                - libglib2.0-bin
                - libqt5core5a
                - libqt5gui5
                - libqt5network5
                - libqt5widgets5
                - libqt5svg5 # for loading icon themes which are svg

                - try: [appmenu-qt5] # not available on core18
                - locales-all
                - xdg-user-dirs
                - fcitx-frontend-qt5
                - qt5-gtk-platformtheme #Platform themes plugin

apps:
    jmbde-qt:
        command: bin/desktop-launch jmbde-qt
        environment:
            DISABLE_WAYLAND: 1
        desktop: usr/share/applications/com.github.jmuelbert/jmbde.desktop
        common-id: com.github.jmuelbert.jmbde-QT

