---
name: jmbde-qt
adopt-info: jmbde
icon: assets/icons/jmbde.png

base: core18
grade: devel
confinement: devmode
compression: lzo

summary: A BDE tool.
description: jmbde is a free bde tool.

version: "0.6.0"

architectures:
  - build-on: amd64
    run-on: amd64
apps:
    jmbde-qt:
        command: jmbde
        common-id: com.github.jmuelbert.jmbde-QT
        extensions:
            - kde-neon
        plugs:
            - home
            - desktop
            - desktop-legacy
            - wayland
            - x11
parts:
    jmbde-qt:
        plugin: cmake
        source: .
        source-type: git
        parse-info:
            - usr/share/metainfo/jmbde.appdata.xml
        build-snaps:
            - kde-frameworks-5-qt-5-15-core20
        build-packages:
            - libmpfr-dev
            - libgmp-dev
            - kdoctools-dev
        stage-packages:
            - libmpfr6
            - libgmp10

        configflags:
            - "-DLGTM=ON"
            - "-DKDE_INSTALL_USE_QT_SYS_PATHS=ON"
            - "-DCMAKE_INSTALL_PREFIX=/usr"
            - "-DCMAKE_BUILD_TYPE=Release"
            - "-DENABLE_TESTING=OFF"
            - "-DBUILD_TESTING=OFF"

