---
# SPDX-FileCopyrightText: Jürgen Mülbert
#
# SPDX-License-Identifier: MIT

name: Auto Assign to Project(s)

on:
  pull_request_target:
    types: [opened, labeled]

permissions:
  pull-requests: write

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project

    steps:
      - name: Assign NEW issues and NEW pull requests to project 10
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: github.event.action == 'opened'
        with:
          project: "10"

      - name: Assign issues and pull requests with `bug` label to project 10
        uses: srggrs/assign-one-project-github-action@1.2.1
        if: contains(github.event.pull_request.labels.*.name, 'bug')
        with:
          project: "10"
          column_name: "Labeled"
