---
# SPDX-FileCopyrightText: Alex Page
#
# SPDX-License-Identifier: MIT

name: Move assigned pull requests into To do

on:
  pull_request:
    types: [assigned]

permissions:
  contents: read

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.9.0
        with:
          project: jmbde-QT
          column: To do
          repo-token: ${{ secrets.GITHUB_TOKEN }}
