---
name: format

# yamllint disable
on:
  # yamllint enable
  push:
    branches: [main, develop]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  format:
    name: "💎 Format"
    runs-on: ubuntu-latest

    steps:
      - name: "🧰 Checkout"
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: "🟨 Use clang-format"
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: "."
          exclude: "./third_party ./external"
          extensions: "h,cpp,hpp"
          clangFormatVersion: 14
          inplace: true

      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Clang Robot
          author_email: robot@example.com
          message: ":art: Committing clang-format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "🟨 Setup Python"
        uses: actions/setup-python@v4
        with:
          # Read python version from a file .python-version
          python-version-file: ".python-version"
          #check-latest: true
          cache: pip

      - name: "🟨 Install cmakelang"
        uses: BSFishy/pip-action@v1
        with:
          packages: cmakelang pyyaml jinja2

      - name: "🟨 Use cmake-format"
        run: find . \( -name '*.cmake' -o -name 'CMakeLists.txt' \) -exec cmake-format -i {} \;

      - name: "📨 Use Commit"
        uses: EndBug/add-and-commit@v4
        with:
          author_name: github_actions
          message: ":art: Committing format changes"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
