---
name: "Check Clang Format"

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Source code
              if: github.event_name == 'push'
              uses: actions/checkout@v2
            - name: Checkout Source code
              if: github.event_name == 'pull_request'
              uses: actions/checkout@v2
              with:
                  ref: ${{ github.event.pull_request.head.sha }}
            - uses: DoozyX/clang-format-lint-action@v0.9
              with:
                  source: "./src"
                  extensions: "h,cpp"
                  clangFormatVersion: 11
                  style: file
            - uses: EndBug/add-and-commit@v4
              with:
                author_name: Clang Robot
                author_email: robot@example.com
                message: 'Committing clang-format changes'
                env:
                   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
