name: "Auto Clang Format"

on:
  push:
    paths-ignore:
      - '*.md'
      - '*/*.md'
      - '*/*/*.md'

jobs:
  build:
    name: "Auto Clang Format"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Install clang-format-9"
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-9
    - name: "Format Codes"
      run: |
        clang-format-9 -i  src/app/src/*.cpp \
                              src/appquick/src/*.cpp \
                              src/libs/models/src/models/*.cpp \
                              src/libs/models/include/models/*.h \
                              src/libs/models/tests/*.cpp \
                              src/libs/quick/src/quick/*.cpp \
                              src/libs/quick/include/quick/*.h \
                              src/libs/quick/tests/*.h \
                              src/libs/quick/tests/*.cpp \
                              src/libs/widgets/src/views/*.cpp \
                              src/libs/widgets/include/views/*.h \
                              src/libs/widgets/tests/*.h \
                              src/libs/widgets/tests/*.cpp \
                              tests/tst_test.cpp \
                              tests/tst_test.h

    - name: Commit files
      run: |
        git config --local user.email "juergen.muelbert@gmail.com"
        git config --local user.name "jmuelbert"
        git diff-index --quiet HEAD || git commit -am "style: Format codes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
