name: "Auto Clang Format"

on:
  push:
    paths-ignore:
      - '*.md'
      - '*/*.md'
      - '*/*/*.md'

jobs:
  build:
    name: "Auto Clang Format"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Install clang-format-9"
      run: |
        sudo apt-get update
        sudo apt-get install clang-format-9
    - name: "Format Codes"
      run: clang-format-9 -i src/*.cpp src/*/*.cpp include/*.h include/*/*.h
    - name: Commit files
      run: |
        git config --local user.email "jmbde_bot@126.com"
        git config --local user.name "jmbde-bot"
        git diff-index --quiet HEAD || git commit -am "style: Format codes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}