name: code-checker
on: [push]

jobs:
  build:
    name: code-checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: cppcheck
        uses: deep5050/cppcheck-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN}}

      - name: Clang Code Formatter
        uses: ivanludvig/clang-format-action@v1.4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: publish report
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master' # your branch name goes here
