---
# SPDX-FileCopyrightText: (c) Wagner Santos
#
# SPDX-License-Identifier: MIT
#
name: Lint Commit Messages
on: [pull_request] # yamllint disable-line rule:truthy

permissions:
  actions: read
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  commitlint:
    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')
    runs-on: ubuntu-latest

    steps:
      - name: 🧰 Checkout Source Code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Check the commits
        uses: wagoid/commitlint-github-action@7f0a61df502599e1f1f50880aaa7ec1e2c0592f2 # v6.0.1
