# SPDX-FileCopyrightText: GitHub, Inc. and contributors
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2022 GitHub, Inc. and contributors

# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a
# Pull Request, surfacing known-vulnerable versions of the packages declared
# or updated in the PR. Once installed, if the workflow run is marked as
# required, PRs introducing known-vulnerable packages will be blocked from
# merging.
#
# Source repository: https://github.com/actions/dependency-review-action
# Public documentation:
# https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
name: Dependency Review
on: pull_request # yamllint disable-line rule:truthy
#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/supply-chain-security/understanding-your-software-supply-chain/using-the-dependency-submission-api
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    permissions:
      # Write permissions for pull-requests are required for using the `comment-summary-in-pr` option, comment out if you aren't using this option
      pull-requests: write
      # If using a dependency submission action in this workflow this permission will need to be set to:
      contents: write
    steps:
      - name: 🧰 Checkout Source Code
        uses: actions/checkout@cbb722410c2e876e24abbe8de2cc27693e501dcb # v4.1.5
      - name: Dependency Review Action
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
        # Commonly enabled options, see https://github.com/actions/dependency-review-action#configuration-options for all available options.
        with:
          comment-summary-in-pr: always
          #   fail-on-severity: moderate
          #   deny-licenses: GPL-1.0-or-later, LGPL-2.0-or-later
          #   retry-on-snapshot-warnings: true
