---
name: docs
on:
  push:
    branches:
      - main

    paths:
      - "README.md"
      - "website/**.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "🧰 Checkout"
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: "Build docs and deploy to gh-pages"
        uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: website
          git-user: jmuelbert_pages_update
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
