name: Check Nix Flake
on:
  pull_request:
    branches: [main]
    paths:
      - '**.nix'
      - .github/workflows/flake-checker.yml
      - flake.lock
  push:
    branches:
      - main
    paths:
      - '**.nix'
      - .github/workflows/flakechecker.yml
      - flake.lock
jobs:
  flake-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/flake-checker-action@v9
