---
name: "Flatpak"

on:
    push:
        branches:
            - "master"
        paths-ignore:
            - 'docs/**'
            - '.github/ISSUE_TEMPLATE/**'
            - 'docker/**'
            - '**.md'
            - '!docs/building-cmake.md'
            - 'changelog.txt'
            - 'LICENSE'
            - '.github/**'
            - '!.github/workflows/flstpak.yml'
            - '!packaging/flatpak/org.jmuelbert.jmbde-QT.yml'
            - 'build/**'
            - 'assets/**'
            - 'Docker/**'
            - 'report/**'
            - 'resources/**'
    pull_request:
        branches:
            - "master"
        types: [opened, reopened]
        paths-ignore:
            - 'docs/**'
            - '.github/ISSUE_TEMPLATE/**'
            - 'docker/**'
            - '**.md'
            - '!docs/building-cmake.md'
            - 'changelog.txt'
            - 'LICENSE'
            - '.github/**'
            - '!.github/workflows/flatpak.yml'
            - '!packaging/flatpak/org.jmuelbert.jmbde-QT.yml'
            - 'build/**'
            - 'assets/**'
            - 'Docker/**'
            - 'report/**'
            - 'resources/**'

    release:
        types: [published]

env:
    QT_VERSION: 5.15.2
    APP_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}
    APP_SNAPSHOT: ${{ !startsWith(github.ref, 'refs/tags/v') }}

jobs:
  version:
    name: Determine App version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      release: ${{ steps.get-version.outputs.release }}

    steps:
    - name: Get version
      id: get-version
      run: |
        if [[ "$APP_RELEASE" == 'true' ]]; then echo "::set-output name=version::${GITHUB_REF:11}" ; fi
        if [[ "$APP_RELEASE" != 'true' ]]; then echo "::set-output name=version::$(date "+%Y.%m.%d")" ; fi
        echo "::set-output name=release::${APP_RELEASE}"

  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-5.15
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      name: "Build"
      with:
        bundle: com.github.rafostar.Clapper.flatpak
        manifest-path: packaging/flatpak/org.jmuelbert.jmbde-QT.yml
        cache-key: flatpak-builder-${{ github.sha }}
