---
name: "CD: flatpak package"

on:
    push:
        branches:
            - "master"
        paths-ignore:
            - "docs/**"
            - ".github/ISSUE_TEMPLATE/**"
            - "docker/**"
            - "**.md"
            - "!docs/building-cmake.md"
            - "changelog.txt"
            - "LICENSE"
            - ".github/**"
            - "!.github/workflows/flatpak.yml"
            - "snap/**"
            - "build/**"
            - "assets/**"
            - "Docker/**"
            - "report/**"
            - "resources/**"
    pull_request:
        branches:
            - "master"
        types: [opened, reopened]
        paths-ignore:
            - "docs/**"
            - ".github/ISSUE_TEMPLATE/**"
            - "docker/**"
            - "**.md"
            - "!docs/building-cmake.md"
            - "changelog.txt"
            - "LICENSE"
            - ".github/**"
            - "!.github/workflows/flatpak.yml"
            - "snap/**"
            - "build/**"
            - "assets/**"
            - "Docker/**"
            - "report/**"
            - "resources/**"

    release:
        types: [published]

env:
    QT_VERSION: 5.15.2
    APP_RELEASE: ${{ startsWith(github.ref, 'refs/tags/v') }}
    APP_SNAPSHOT: ${{ !startsWith(github.ref, 'refs/tags/v') }}

jobs:
    version:
        name: Determine App version
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.get-version.outputs.version }}
            release: ${{ steps.get-version.outputs.release }}

        steps:
            - name: Get version
              id: get-version
              run: |
                  if [[ "$APP_RELEASE" == 'true' ]]; then echo "::set-output name=version::${GITHUB_REF:11}" ; fi
                  if [[ "$APP_RELEASE" != 'true' ]]; then echo "::set-output name=version::$(date "+%Y.%m.%d")" ; fi
                  echo "::set-output name=release::${APP_RELEASE}"

    flatpak:
        name: "Flatpak"
        runs-on: ubuntu-latest
        container:
            image: bilelmoussaoui/flatpak-github-actions:kde-5.15
            options: --privileged
        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: recursive
            - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
              name: "Build"
              with:
                  bundle: org.jmuelbert.jmbde-QT.flatpak
                  manifest-path: packaging/flatpak/org.jmuelbert.jmbde-QT.yml
                  cache-key: flatpak-builder-${{ github.sha }}

            - name: SHA256Sum of flatpak package(daily build)
              run: |
                  sha256sum $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak
                  sha256sum $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak > $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak.sha256sum
                  echo "================flatpak sha256sum download link===================="
                  echo $(sh $GITHUB_WORKSPACE/scripts/upload_services/${UPLOAD_SERVICE}.sh $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak.sha256sum)
                  echo "========no operation for you can see link in the log console======="
            - name: Upload flatpak package(daily build)
              run: |
                  echo "=====================flatpak download link====================="
                  echo $(sh $GITHUB_WORKSPACE/scripts/upload_services/${UPLOAD_SERVICE}.sh $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak0)
                  echo "======no operation for you can see link in the log console====="
            - name: Artifact Upload
              uses: actions/upload-artifact@v2.2.4
              with:
                  name: Linux-distribution-artifact
                  path: |
                      ${{ github.workspace }}/org.jmuelbert.jmbde-QT-*.x86_64.flatpak
                      ${{ github.workspace }}/org.jmuelbert.jmbde-QT-*.x86_64.flatpak.sha256sum
