---
name: "CD: flatpak package"

on:
    push:
        branches:
            - "master"
        paths-ignore:
            - 'docs/**'
            - '.github/ISSUE_TEMPLATE/**'
            - 'docker/**'
            - '**.md'
            - '!docs/building-cmake.md'
            - 'changelog.txt'
            - 'LICENSE'
            - '.github/**'
            - '!.github/workflows/flatpak.yml'
            - 'snap/**'
            - 'build/**'
            - 'assets/**'
            - 'Docker/**'
            - 'report/**'
            - 'resources/**'
    pull_request:
        branches:
            - "master"
        types: [opened, reopened]
        paths-ignore:
            - 'docs/**'
            - '.github/ISSUE_TEMPLATE/**'
            - 'docker/**'
            - '**.md'
            - '!docs/building-cmake.md'
            - 'changelog.txt'
            - 'LICENSE'
            - '.github/**'
            - '!.github/workflows/flatpak.yml'
            - 'snap/**'
            - 'build/**'
            - 'assets/**'
            - 'Docker/**'
            - 'report/**'
            - 'resources/**'

    release:
        types: [published]

env:
    PRODUCT: jmbde
    targetName: jmbde
    QT_VERSION: 5.15.2

jobs:
    check_commit_msg:
        outputs:
            commit_message: ${{ steps.get_message.outputs.message }}
        name: Check if the workflow has been disabled.
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Get commit message
              id: get_message
              run: |
                  echo "::set-output name=message::$(git log --format=%B -n 1 ${{ github.event.after }})"
    build:
        needs: check_commit_msg
        if: ${{ !contains( needs.check_commit_msg.outputs.commit_message, 'NO_MAIN') }}
        strategy:
            matrix:
                platform: [ubuntu-latest]
                build_type: [Release]
                arch: [x64]
            fail-fast: false

        runs-on: ${{ matrix.platform }}

        steps:
            - name: Checkout Source code
              if: github.event_name == 'push'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: master
            - name: Checkout Source code
              if: github.event_name == 'pull_request'
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.sha }}
            - name: Set env & Print jmbde version
              shell: bash
              run: |
                  last_committed_tag=$(git tag -l --sort=-v:refname | head -1)
                  git_revno=$(git rev-list $(git describe --tags --abbrev=0)..HEAD --count)
                  git_hash=$(git rev-parse --short HEAD)
                  echo "======= jmbde-QT VERSION ========"
                  echo ${last_committed_tag:1}
                  echo "Details: ${last_committed_tag}+git${git_revno}.${git_hash}"
                  echo "================================"
                  echo "VERSION=${last_committed_tag:1}" >> $GITHUB_ENV
            - name: Setup flatpak
              run: |
                  sudo apt-get -y -qq update
                  sudo apt-get install -y flatpak flatpak-builder
            - name: Setup Flathub
              run: |
                  flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
                  # flatpak install -y --noninteractive flathub org.kde.Sdk//5.15 org.kde.Platform//5.15
                  flatpak install -y flathub org.kde.Sdk//5.15 org.kde.Platform//5.15
            - name: Packaging flatpak
              run: |
                  mkdir build
                  BUNDLE="org.jmuelbert.jmbde-QT_${VERSION}_x86_64.flatpak"
                  MANIFEST_PATH=$GITHUB_WORKSPACE/packaging/flatpak/org.jmuelbert.jmbde-QT.yml
                  RUNTIME_REPO="https://flathub.org/repo/flathub.flatpakrepo"
                  APP_ID="org.jmuelbert.jmbde-QT"
                  BRANCH="master"
                  flatpak-builder --user --disable-rofiles-fuse --repo=repo --force-clean flatpak_app ${MANIFEST_PATH} --install-deps-from=flathub ./build
                  flatpak build-bundle repo ${BUNDLE} --runtime-repo=${RUNTIME_REPO} ${APP_ID} ${BRANCH}
                  mv $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT_${VERSION}_x86_64.flatpak $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak
            - name: SHA256Sum of flatpak package(daily build)
              run: |
                  sha256sum $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak
                  sha256sum $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak > $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak.sha256sum
                  echo "================flatpak sha256sum download link===================="
                  echo $(sh $GITHUB_WORKSPACE/scripts/upload_services/${UPLOAD_SERVICE}.sh $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak.sha256sum)
                  echo "========no operation for you can see link in the log console======="
            - name: Upload flatpak package(daily build)
              run: |
                  echo "=====================flatpak download link====================="
                  echo $(sh $GITHUB_WORKSPACE/scripts/upload_services/${UPLOAD_SERVICE}.sh $GITHUB_WORKSPACE/org.jmuelbert.jmbde-QT-${VERSION}.x86_64.flatpak0)
                  echo "======no operation for you can see link in the log console====="
            - name: Artifact Upload
              uses: actions/upload-artifact@v2.2.4
              with:
                  name: Linux-distribution-artifact
                  path: |
                      ${{ github.workspace }}/org.jmuelbert.jmbde-QT-*.x86_64.flatpak
                      ${{ github.workspace }}/org.jmuelbert.jmbde-QT-*.x86_64.flatpak.sha256sum
