
on:
  schedule:
    - cron: "0 0 * * *"
name: "Flatpak Testing"
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
      name: "Build"
      with:
        bundle: org.jmuelbert.jmbde-QT.flatpak
        manifest-path: packaging/flatpak/org.jmuelbert.jmbde-QT.yml
        cache-key: flatpak-builder-${{ github.sha }}-testing-${{ github.run_number }}
