name: Doxygen CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: brew update-reset
        run: brew update-reset
      - name: brew update
        run: brew update
      - name: brew install kde-extra-cmake-modules
        run: |
            brew tap kde-mac/kde https://invent.kde.org/packaging/homebrew-kde.git --force-auto-update
            brew install kde-extra-cmake-modules
      - name: Upgrade cmake and ninja
        run: |
            brew upgrade cmake
            brew ls | grep wq ninja || brew install ninja
      - name: Install dependencies with homebrew
        run: |
            brew install graphviz doxygen
            brew ls | grep -wq freetype || brew install freetype
            brew ls | grep -wq python || brew install python
            brew ls | grep -wq qt || brew install qt
            export PATH="$(brew --prefix qt)/bin:$PATH"
            pip install sphinx sphinx-rtd-theme breathe
      - name: configure
        run: cmake -G Ninja  -DCMAKE_PREFIX_PATH="$(brew --prefix qt)" -B ./build -S .
      - name: build
        run: cd build && ninja Sphinx
      - name: gh-pages
        uses: actions/checkout@master
        with:
          ref: "gh-pages"
          clean: false
      - name: Move & Commit files
        run: |
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          rm -rf d* && rm *.html && rm *.svg && rm *.map && rm *.md5 && rm *.png && rm *.js && rm *.css
          git add .
          cp -rp ./build/html/* . && rm -rf ./build && ls -lah
          git add .
          git commit -m "Documentation for $GITHUB_SHA" ||  true
          git push --force || true
