name: Flake ❄️ Lock 🔒️ Updater ✨
on:
  schedule:
    # Run on the third of the month
    - cron: 0 0 3 * *
  workflow_dispatch:
jobs:
  lock-updater:
    name: Flake Lock Updater
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: DeterminateSystems/update-flake-lock@v24
        with:
          pr_assignees: ${{ github.repository_owner }}
          pr_labels: |
            automated
            dependencies
          pr_title: "chore: update flake.lock"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
