name: Compile on latest macOS
on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest
  
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          brew tap kde-mac/kde
          brew install qt cmake ninja
          brew link qt5 --force
          brew install kf5-extra-cmake-modules
      - name: Build
        run: |
          export JMBDE_VERSION=$(git describe | cut -c 2-)
          mkdir build && cd build
          cmake -GNinja -DCMAKE_PREFIX_PATH="$(brew --prefix qt)" -DCMAKE_INSTALL_PREFIX=install -DBUILD_SHARED_LIBS=ON ..
          cmake --build . --config $CMAKE_BUILD_TYPE --target install
      - name: Package
        run: |
          export VERSION=$(git rev-parse --short HEAD);
          pwd
          ls
          macdeployqt install/jmbde.app -verbose=2
          mkdir -p dmgdir/jmbde.app;
          cp -r install/jmbde.app/* dmgdir/jmbde.app/
          ln -s /Applications dmgdir/Applications;
          hdiutil create -volname jmbde-$VERSION -srcfolder dmgdir -ov -format UDZO jmbde-$VERSION.dmg
      - uses: actions/upload-artifact@v1
        with:
          name: jmbde*.dmg
          path: jmbde*.dmg

