name: "CD: MacOS"
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'BUILD.md'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'BUILD.md'
  release:
    types: [published]
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        build_type: [Release, RelWithDebInfo]
        qt_ver: [5.15.2]
        qt_arch: [clang_64]
    env:
      targetName: jmbde
    steps:

      - name: Restore Qt from cache
        id: cache-qt
        uses: actions/cache@v2.1.3
        with:
          path: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
          key: ${{ runner.os }}-Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}

      - name: Set up Qt environment
        uses: jurplel/install-qt-action@v2
        with:
            cached: ${{ steps.cache-qt.outputs.cache-hit }}
            version: ${{ env.QT_VERSION }}

      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: macOS - ${{ matrix.qt_version }} - Build preparation - Install Packages
        run: |
          brew install ninja pkg-config

      - name: conan_and_ecm
        id: conan_and_ecm
        run: |
            python3 -m pip install conan
            conan user
            conan create ./conan/ecm
            mkdir build
            cd build
            conan install ..
            cd ..
      - name: build macos
        env:
          Qt5_DIR: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
        run: |
          cd build
          cmake .. \
            -GNinja \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -DJMBDE_QT6=OFF \
            -DJMBDE_BUILD_INFO="Build for macOS" \
            -DJMBDE_BUILD_EXTRA_INFO="Build on $(uname -sr)" \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=10.14 \
            -DBUILD_TRANSLATIONS=ON \
            -DCMAKE_INSTALL_PREFIX:PATH=./app
          cmake --build . --parallel $(sysctl -n hw.logicalcpu)
          cmake --install .
      - name: package
        env:
          Qt5_DIR: ../Qt/${{matrix.qt_ver}}/${{matrix.qt_arch}}
        run: |
          #mv ${targetName} ${targetName}.app
          cd build
          export PATH=$Qt5_DIR/bin:$PATH
          macdeployqt ./app/${targetName}.app -qmldir=. -appstore-compliant -libpath=./app/jmbde.app/Contents/Frameworks -verbose=1 -dmg
          cp ./app/${targetName}.dmg ${targetName}-Qt${{matrix.qt_ver}}.dmg
      - name: Upload artifact
        uses: actions/upload-artifact@v2-preview
        with:
          name: ${{env.targetName}}-Qt${{matrix.qt_ver}}.dmg
          path: build/${{env.targetName}}-Qt${{matrix.qt_ver}}.dmg
      - name: uploadRelease
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/${{env.targetName}}-Qt${{matrix.qt_ver}}.dmg
          asset_name: ${{env.targetName}}.dmg ${targetName}-Qt${{matrix.qt_ver}}.dmg
          tag: ${{ github.ref }}
