---
# SPDX-FileCopyrightText: Nikita Sobolev
#
# SPDX-License-Identifier: MIT
#
name: Misspell fixer

on:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

permissions:
  contents: read

jobs:
  misspell-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: sobolevn/misspell-fixer-action@master
      - name: "Check diff"
        run: git diff --exit-code ${{ github.sha }}
      - uses: peter-evans/create-pull-request@v5
        if: failure()
        with:
          commit-message: "Fix typos by misspell-fixer"
          title: "Fix typos by misspell-fixer for ${{ github.ref }}"
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          branch: "auto-pr/misspell-fixer/${{ github.ref }}"
