---
# SPDX-FileCopyrightText: Jürgen Mülbert
#
# SPDX-License-Identifier: MIT

name: "Misspell fixer"

on: # yamllint disable-line rule:truthy
  push:
    branches: [main, develop, release, improve_workflows]

  pull_request:
    # The branches below must be a subset of the branches above
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  misspell-fixer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: "🧰 Checkout Source Code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # Full git history is needed to get a proper list of changed
          # files within `super-linter`
          fetch-depth: 0

      - name: Run Misspell Fixer
        uses: sobolevn/misspell-fixer-action@8842a5615f83fed75e8a87015e9300a54d049961 # master

      - name: Check for changes
        run: git diff --exit-code ${{ github.sha }}

      - name: Create Pull Request for typos
        if: failure()
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v5.0.2
        with:
          commit-message: "Fix typos by misspell-fixer"
          title: "Fix typos by misspell-fixer for ${{ github.ref }}"
          assignees: ${{ github.actor }}
          reviewers: ${{ github.actor }}
          branch: "auto-pr/misspell-fixer/${{ github.ref }}"
