---
# SPDX-FileCopyrightText: Jef LeCompte
#
# SPDX-License-Identifier: MIT
#
name: Pull Request Linter
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  lint-pr:
    name: Lint pull request title
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: '🧰 Check out code'
        uses: actions/checkout@v4

      - name: Lint pull request title
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
