---
# SPDX-FileCopyrightText: Jan Amann
#
# SPDX-License-Identifier: MIT
#

name: Pull Request Linter

on:
  pull_request:
    # The branches below must be a subset of the branches above
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  lint-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
