---
# SPDX-FileCopyrightText: GitHub, Inc. and contributors
#
# SPDX-License-Identifier: MIT
#
# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
# yamllint disable
on:
  # yamllint enable
  pull_request:
    # The branches below must be a subset of the branches above
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/pr-labeler.yml
          sync-labels: false
