name: "Release checksums"

on:
    release:
        types:
            - published

jobs:
    build:
        name: "Release checksums"
        runs-on: "ubuntu-latest"

        steps:
            - uses: actions/checkout@v2

            - name: Get the version
              id: get_version
              run: |
                  VERSION=${GITHUB_REF/refs\/tags\//}
                  echo ::set-output name=VERSION::$VERSION
                  read STABLE_VERSION < .ci/STABLE_VERSION
                  if [ "${VERSION:0:${#STABLE_VERSION}}" == "$STABLE_VERSION" ]; then
                    echo ::set-output name=ISBETA::false
                  else
                    echo ::set-output name=ISBETA::true
                  fi
