
name: Compile on latest Ubuntu

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: install dependencies
      run: |
        sudo apt update
        sudo apt-get -y install cmake
        sudo apt-get -y install ninja-build
        sudo apt-get -y install libgl1-mesa-dev
        sudo add-apt-repository ppa:beineri/opt-qt-5.12.7-bionic -y
        sudo apt-get update -qq
        sudo apt-get -y install qt512base libgl1-mesa-dev qt512svg qt512imageformats
        bash /opt/qt*/bin/qt*-env.sh
        sudo pip3 install conan
        conan user
        conan create ./conan/ECM
    - name: build
      run: |
          mkdir -p build
          mkdir -p appbuild
          mkdir -p appdir
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX:PATH=/usr -DBUILD_SHARED_LIBS=ON -DENABLE_TESTING=ON
          make
          ctest -V
          cd ../appbuild
          cmake -DCMAKE_INSTALL_PREFIX:PATH=../appdir/usr -Wno-dev ..
          make install
          cd ..
          export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/appdir/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH
          git rev-list master --count
          wget -c "https://github.com/jimevins/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt*.AppImage
          wget -c -nv "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
          chmod a+x appimagetool-x86_64.AppImage
          ./linuxdeployqt*.AppImage appdir/usr/share/applications/*.desktop -bundle-non-qt-libs -extra-plugins=imageformats/libqsvg.so -exclude-libs=libpython3.54m.so.1.0 -verbose=2 -appimage
          find appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
