---
name: Update Changelog file

# on: [workflow_dispatch]
on:
    push:
        branches:
            - master*
        paths-ignore:
            - "README.md"
            - "LICENSE"

    pull_request:
        paths-ignore:
            - "README.md"
            - "LICENSE"

env:
    PRODUCT: jmbde
    targetName: jmbde
    RUNNER_DEBUG: 1

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
       - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
         with:
            token: ${{ secrets.GITHUB_TOKEN }}
