# SPDX-FileCopyrightText: Tom Ross
#
# SPDX-License-Identifier: MIT
#
name: "Write good"
on:
  push:
    branches: [main, develop, release, improve_build-workflow]
  pull_request:
    # The branches below must be a subset of the branches above
    types: [opened, synchronize, reopened]

permissions:
  contents: read
jobs:
  write_good_job:
    runs-on: ubuntu-latest
    name: A job to lint Markdown files
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "🧰 Checkout Source Code"
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: write-good action step
        id: write-good
        uses: tomwhross/write-good-action@5897a4ff597390bd521c5c3a6c062bf96147a341 # v1.6
      # Use the output from the `write-good` step
      - name: Get the write-good output
        run: echo "${{ steps.write-good.outputs.result }}"
      - name: Post comment
        uses: mshick/add-pr-comment@7c0890544fb33b0bdd2e59467fbacb62e028a096 # v2.8.1
        if: ${{ steps.write-good.outputs.result }}
        with:
          message: |
            ${{ steps.write-good.outputs.result }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-repeats: false # This is the default
