cloud-native-image:
    extends: .cng:rules
    image: ${GITLAB_DEPENDENCY_PROXY}ruby:2.7-alpine
    dependencies: []
    stage: post-test
    variables:
        GIT_DEPTH: "1"
    script:
        - install_gitlab_gem
        - ./scripts/trigger-build cng
