.tests-metadata-state:
    image: ${GITLAB_DEPENDENCY_PROXY}ruby:2.7
    before_script:
        - source scripts/utils.sh
    artifacts:
        expire_in: 31d
        paths:
            - knapsack/
            - rspec_flaky/
            - rspec_profiling/
            - crystalball/packed-mapping.json.gz

retrieve-tests-metadata:
    extends:
        - .tests-metadata-state
        - .test-metadata:rules:retrieve-tests-metadata
    stage: prepare
    script:
        - install_gitlab_gem
        - source ./scripts/rspec_helpers.sh
        - retrieve_tests_metadata

update-tests-metadata:
    extends:
        - .tests-metadata-state
        - .test-metadata:rules:update-tests-metadata
    stage: post-test
    dependencies:
        - retrieve-tests-metadata
        - setup-test-env
        - rspec migration pg12
        - rspec frontend_fixture
        - rspec-ee frontend_fixture
        - rspec unit pg12
        - rspec integration pg12
        - rspec system pg12
        - rspec-ee migration pg12
        - rspec-ee unit pg12
        - rspec-ee integration pg12
        - rspec-ee system pg12
        - rspec-ee unit pg12 geo
        - rspec-ee integration pg12 geo
        - rspec-ee system pg12 geo
    script:
        - run_timed_command "retry gem install fog-aws mime-types activesupport rspec_profiling postgres-copy --no-document"
        - source ./scripts/rspec_helpers.sh
        - update_tests_metadata
        - update_tests_mapping
