# Yamllint of CI-related yaml and changelogs.
# This uses rules from project root `.yamllint`.
lint-yaml:
    extends:
        - .default-retry
        - .yaml-lint:rules
    image: pipelinecomponents/yamllint:latest
    stage: test
    needs: []
    variables:
        LINT_PATHS: .gitlab-ci.yml .gitlab/ci lib/gitlab/ci/templates changelogs
    script:
        - yamllint -f colored $LINT_PATHS
